# EPL Championship

## Scraping and Cleaning

In [1]:
# Import all the necessary libraries

import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools

%matplotlib inline

In [2]:
# Read data from the CSV into a dataframe

loc = "./Datasets_Championship/"

raw_data_1 = pd.read_csv(loc + '2004_05_champions_UTF.csv')
raw_data_2 = pd.read_csv(loc + '2005_06_champions.csv')
raw_data_3 = pd.read_csv(loc + '2006_07_champions.csv')
raw_data_4 = pd.read_csv(loc + '2007_08_champions.csv')
raw_data_5 = pd.read_csv(loc + '2008_09_champions.csv')
raw_data_6 = pd.read_csv(loc + '2009_10_champions.csv')
raw_data_7 = pd.read_csv(loc + '2010_11_champions.csv')
raw_data_8 = pd.read_csv(loc + '2011_12_champions.csv')
raw_data_9 = pd.read_csv(loc + '2012_13_champions.csv')
raw_data_10 = pd.read_csv(loc + '2013_14_champions.csv')
raw_data_11 = pd.read_csv(loc + '2014_15_champions.csv')
raw_data_12 = pd.read_csv(loc + '2015_16_champions.csv')
raw_data_13 = pd.read_csv(loc + '2016_17_champions.csv')
raw_data_14 = pd.read_csv(loc + '2017_18_champions.csv')

# teamNames_dic_by_year = []

number_of_teams_in_EFL_Championship = 24
number_of_teams_in_EPL              = 20
number_of_teams_in_primeira_liga    = 18


number_of_teams = number_of_teams_in_EFL_Championship

In [3]:
from IPython.display import display

pd.set_option('display.max_columns', None)
display(raw_data_14.head(400))

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E1,04/08/17,Nott'm Forest,Millwall,1,0,H,1,0,H,P Bankes,11,23,2,6,13,15,5,4,0,1,0,0,2.00,3.60,4.00,1.90,3.50,3.90,1.95,3.35,3.70,2.05,3.40,3.90,2.06,3.48,3.96,2.00,3.30,3.80,2.05,3.60,3.90,41,2.10,2.01,3.60,3.42,4.20,3.80,39,2.13,2.04,1.84,1.76,20,-0.50,2.06,2.01,1.90,1.86,1.98,3.50,4.25
1,E1,04/08/17,Sunderland,Derby,1,1,D,1,1,D,O Langford,20,11,4,4,12,11,6,7,1,0,0,0,2.70,3.25,2.88,2.65,3.10,2.85,2.55,3.10,2.75,2.65,3.20,2.90,2.68,3.26,2.90,2.62,3.10,2.80,2.63,3.25,2.90,41,2.75,2.61,3.35,3.16,2.95,2.84,39,2.29,2.20,1.75,1.66,19,0.00,1.91,1.84,2.07,2.02,2.77,3.16,2.84
2,E1,05/08/17,Aston Villa,Hull,1,1,D,1,0,H,A Madley,12,14,5,5,13,11,5,3,2,0,0,0,2.10,3.40,4.00,2.05,3.20,3.70,2.00,3.20,3.75,2.05,3.10,3.70,2.09,3.39,3.97,2.00,3.40,3.80,2.10,3.40,4.00,41,2.10,2.05,3.40,3.30,4.06,3.78,35,2.41,2.28,1.65,1.60,18,-0.50,2.09,2.05,1.85,1.82,1.96,3.39,4.64
3,E1,05/08/17,Bristol City,Barnsley,3,1,H,3,0,H,A Davies,20,10,11,5,14,9,3,2,1,2,0,0,1.83,3.75,4.75,1.83,3.50,4.20,1.80,3.60,4.15,1.80,3.60,4.20,1.85,3.81,4.51,1.83,3.50,4.33,1.87,3.75,4.50,41,1.87,1.83,3.81,3.65,4.75,4.26,39,1.85,1.78,2.08,2.01,18,-0.50,1.85,1.82,2.11,2.05,1.61,4.18,6.30
4,E1,05/08/17,Burton,Cardiff,0,1,A,0,0,D,G Eltringham,3,16,0,6,13,15,4,6,1,0,0,0,3.10,3.30,2.50,2.80,3.25,2.45,2.95,3.10,2.40,3.00,3.10,2.40,3.15,3.26,2.49,3.00,3.10,2.50,3.13,3.30,2.50,41,3.15,3.02,3.30,3.17,2.60,2.44,35,2.31,2.24,1.67,1.62,17,0.25,1.84,1.79,2.13,2.08,3.26,3.27,2.45
5,E1,05/08/17,Fulham,Norwich,1,1,D,1,0,H,J Linington,16,19,3,5,12,10,7,1,3,2,0,0,2.05,3.75,3.75,2.00,3.40,3.60,2.00,3.55,3.40,2.00,3.60,3.40,2.05,3.81,3.64,2.05,3.50,3.50,2.10,3.70,3.60,41,2.10,2.03,3.81,3.60,3.75,3.51,39,1.80,1.69,2.28,2.13,18,-0.50,2.08,2.02,1.88,1.84,2.04,3.84,3.71
6,E1,05/08/17,Ipswich,Birmingham,1,0,H,0,0,D,T Robinson,12,12,2,3,11,14,8,2,1,1,0,0,2.50,3.40,3.00,2.30,3.20,3.10,2.35,3.10,2.95,2.40,3.10,3.00,2.47,3.30,3.16,2.40,3.10,3.10,2.45,3.40,3.10,41,2.55,2.44,3.40,3.19,3.16,3.02,36,2.27,2.18,1.72,1.65,17,-0.25,2.12,2.08,1.83,1.79,2.75,3.16,2.94
7,E1,05/08/17,Preston,Sheffield Weds,1,0,H,0,0,D,T Harrington,11,6,3,1,17,18,6,3,2,3,0,0,3.00,3.20,2.63,2.95,3.25,2.35,2.85,3.10,2.45,2.90,3.10,2.50,3.01,3.30,2.57,2.80,3.10,2.62,3.00,3.30,2.55,41,3.10,2.92,3.30,3.18,2.63,2.50,35,2.23,2.16,1.73,1.66,16,0.00,2.12,2.07,1.84,1.80,2.97,3.22,2.68
8,E1,05/08/17,QPR,Reading,2,0,H,1,0,H,S Duncan,11,4,4,2,17,12,10,1,1,2,0,1,2.50,3.40,3.00,2.40,3.20,2.95,2.35,3.20,2.90,2.37,3.25,3.00,2.48,3.41,3.04,2.50,3.20,2.90,2.45,3.40,3.10,41,2.55,2.42,3.41,3.28,3.10,2.96,38,2.05,1.99,1.88,1.79,18,-0.25,2.11,2.06,1.86,1.81,2.39,3.40,3.25
9,E1,05/08/17,Sheffield United,Brentford,1,0,H,1,0,H,S Martin,9,12,2,5,6,9,6,3,0,0,0,0,2.20,4.00,3.10,2.10,3.40,3.30,2.10,3.50,3.15,2.15,3.30,3.30,2.17,3.71,3.40,2.20,3.30,3.30,2.20,3.60,3.40,41,2.25,2.15,4.00,3.53,3.40,3.25,39,1.85,1.74,2.19,2.05,17,-0.25,1.91,1.87,2.04,1.99,2.34,3.64,3.14
10,E1,05/08/17,Wolves,Middlesbrough,1,0,H,1,0,H,D Bond,10,5,2,2,14,13,4,4,1,2,0,0,2.70,3.25,2.88,2.55,3.20,2.75,2.50,3.10,2.80,2.50,3.00,2.80,2.66,3.29,2.90,2.62,3.10,2.80,2.63,3.25,2.90,41,2.70,2.57,3.30,3.16,3.00,2.85,32,2.32,2.23,1.68,1.62,17,0.00,1.86,1.83,2.09,2.04,2.43,3.28,3.29
11,E1,06/08/17,Bolton,Leeds,2,3,A,1,3,A,S Hooper,10,11,4,5,9,14,6,8,1,0,0,0,3.00,3.40,2.50,2.80,3.25,2.45,2.75,3.15,2.50,2.80,3.00,2.50,2.89,3.33,2.64,2.90,3.20,2.50,2.88,3.30,2.50,39,3.00,2.82,3.40,3.22,2.65,2.53,36,2.24,2.14,1.76,1.68,16,0.00,2.11,2.03,1.88,1.83,3.38,3.32,2.36
12,E1,12/08/17,Barnsley,Ipswich,1,2,A,1,0,H,G Eltringham,25,9,10,2,11,14,11,7,1,2,0,0,2.55,3.30,3.00,2.45,3.20,2.85,2.40,3.15,2.85,2.45,3.10,2.90,2.50,3.33,3.08,2.60,3.10,2.80,2.55,3.25,3.00,41,2.60,2.47,3.33,3.20,3.08,2.92,39,2.16,2.06,1.81,1.74,17,-0.25,2.20,2.11,1.82,1.77,2.74,3.36,2.80
13,E1,12/08/17,Birmingham,Bristol City,2,1,H,1,1,D,D Bond,18,25,8,3,15,15,2,10,0,2,1,0,2.55,3.50,2.90,2.50,3.20,2.80,2.45,3.20,2.80,2.50,3.25,2.80,2.59,3.35,2.94,2.40,3.20,3.00,2.55,3.30,2.90,41,2.60,2.49,3.50,3.25,3.00,2.87,40,2.08,1.99,1.87,1.80,20,0.00,1.85,1.80,2.12,2.07,2.53,3.33,3.08
14,E1,12/08/17,Brentford,Nott'm Forest,3,4,A,1,2,A,J Linington,20,13,9,6,11,13,12,3,1,3,0,0,1.85,3.75,4.50,1.80,3.40,4.50,1.80,3.70,4.00,1.83,3.70,4.00,1.85,3.87,4.41,1.80,3.50,4.00,1.87,3.80,4.33,41,1.87,1.83,3.87,3.72,4.50,4.14,36,1.70,1.66,2.27,2.18,19,-0.50,1.86,1.82,2.11,2.04,1.74,4.02,5.08
15,E1,12/08/17,Cardiff,Aston Villa,3,0,H,1,0,H,T Robinson,15,10,12,1,9,9,4,7,0,1,0,0,2.70,3.20,2.90,2.55,3.20,2.75,2.50,3.05,2.80,2.62,3.00,2.80,2.65,3.17,3.01,2.70,3.00,2.80,2.70,3.20,2.90,41,2.70,2.60,3.20,3.08,3.01,2.87,35,2.49,2.37,1.60,1.56,18,0.00,1.88,1.83,2.08,2.03,2.57,3.18,3.15
16,E1,12/08/17,Derby,Wolves,0,2,A,0,1,A,L Probert,13,12,3,3,6,10,10,5,0,0,0,0,2.40,3.25,3.30,2.20,3.20,3.30,2.25,3.00,3.25,2.35,3.00,3.25,2.39,3.15,3.46,2.30,3.20,3.20,2.40,3.20,3.40,41,2.40,2.33,3.30,3.10,3.50,3.28,35,2.60,2.44,1.57,1.52,19,-0.25,2.05,2.00,1.91,1.86,2.58,3.14,3.18
17,E1,12/08/17,Hull,Burton,4,1,H,1,1,D,D England,27,6,11,2,13,6,5,2,2,1,0,1,1.67,3.80,6.00,1.60,3.90,5.25,1.60,3.70,5.25,1.61,3.70,5.75,1.65,3.95,6.10,1.62,3.60,6.00,1.67,3.80,6.00,41,1.70,1.63,3.95,3.76,6.10,5.59,39,2.13,2.03,1.85,1.76,19,-0.75,1.86,1.82,2.11,2.04,1.77,3.78,5.27
18,E1,12/08/17,Leeds,Preston,0,0,D,0,0,D,S Duncan,12,9,4,1,14,14,6,4,1,1,0,1,2.05,3.50,4.00,2.05,3.25,3.60,2.00,3.25,3.65,2.00,3.25,3.80,2.07,3.44,3.98,2.05,3.30,3.75,2.05,3.40,4.00,41,2.07,2.04,3.50,3.34,4.00,3.76,39,2.20,2.09,1.79,1.71,19,-0.50,2.08,2.03,1.87,1.83,2.02,3.60,4.04
19,E1,12/08/17,Middlesbrough,Sheffield United,1,0,H,1,0,H,P Bankes,15,7,2,3,19,11,4,3,1,1,0,0,1.91,3.50,4.75,1.85,3.40,4.25,1.85,3.30,4.25,1.83,3.30,4.50,1.88,3.38,5.02,1.83,3.40,4.50,1.91,3.50,4.60,41,1.91,1.87,3.50,3.36,5.02,4.50,37,2.29,2.19,1.71,1.65,19,-0.50,1.90,1.87,2.04,1.99,2.00,3.34,4.52
20,E1,12/08/17,Millwall,Bolton,1,1,D,0,0,D,A Davies,14,5,8,2,14,16,4,0,2,3,0,0,2.10,3.40,4.00,2.00,3.25,3.75,1.95,3.30,3.75,2.00,3.30,3.80,2.02,3.49,4.10,2.00,3.30,3.80,2.05,3.40,3.90,40,2.10,2.02,3.50,3.35,4.10,3.79,39,2.13,2.05,1.81,1.74,19,-0.50,2.05,2.01,1.90,1.85,1.90,3.46,4.88
21,E1,12/08/17,Reading,Fulham,1,1,D,0,0,D,S Hooper,23,6,6,3,18,7,9,3,3,1,0,1,3.75,3.75,2.05,3.50,3.50,2.00,3.35,3.55,2.00,3.40,3.60,2.00,3.61,3.72,2.09,3.30,3.50,2.10,3.50,3.75,2.10,41,3.75,3.46,3.75,3.59,2.10,2.05,36,1.69,1.64,2.26,2.20,19,0.50,1.85,1.82,2.09,2.05,3.68,3.52,2.16
22,E1,12/08/17,Sheffield Weds,QPR,1,1,D,0,1,A,C Kavanagh,14,10,4,4,10,16,4,1,0,3,0,0,1.83,3.60,5.00,1.75,3.50,4.60,1.75,3.50,4.40,1.80,3.50,4.60,1.86,3.52,4.90,1.80,3.50,4.50,1.80,3.60,4.80,41,1.87,1.81,3.60,3.50,5.00,4.56,40,2.12,2.03,1.84,1.76,19,-0.50,1.86,1.80,2.11,2.06,1.88,3.58,4.80
23,E1,13/08/17,Norwich,Sunderland,1,3,A,0,1,A,A Madley,14,9,3,5,16,18,13,1,0,1,0,0,1.85,3.75,4.50,1.80,3.60,4.25,1.80,3.55,4.15,1.80,3.60,4.33,1.81,3.88,4.62,1.80,3.50,4.50,1.85,3.75,4.60,39,1.86,1.82,3.88,3.64,4.62,4.31,37,1.96,1.87,2.00,1.91,20,-0.50,1.85,1.81,2.11,2.06,1.96,3.76,4.08
24,E1,15/08/17,Barnsley,Nott'm Forest,2,1,H,1,1,D,T Harrington,13,26,5,7,13,9,2,9,2,1,0,0,2.88,3.50,2.55,2.75,3.30,2.50,2.70,3.35,2.45,2.75,3.50,2.55,2.86,3.42,2.64,2.70,3.30,2.60,2.88,3.50,2.55,39,2.88,2.76,3.53,3.38,2.64,2.52,35,1.81,1.72,2.19,2.10,19,0.00,2.08,2.03,1.88,1.83,3.04,3.66,2.39
25,E1,15/08/17,Birmingham,Bolton,0,0,D,0,0,D,D England,10,12,0,2,13,8,7,4,1,1,0,0,1.91,3.40,4.75,1.80,3.40,4.60,1.85,3.30,4.20,1.91,3.40,4.50,1.93,3.45,4.74,1.91,3.30,4.33,1.83,3.50,4.50,39,1.96,1.89,3.50,3.36,4.75,4.38,37,2.25,2.14,1.74,1.69,20,-0.50,1.94,1.90,2.01,1.96,1.93,3.38,4.84
26,E1,15/08/17,Brentford,Bristol City,2,2,D,0,1,A,P Bankes,24,8,10,5,16,13,5,3,2,3,0,0,2.05,3.90,3.50,2.05,3.40,3.50,2.00,3.65,3.25,2.05,3.80,3.40,2.04,3.92,3.63,2.00,3.75,3.40,2.10,3.90,3.40,39,2.10,2.02,3.93,3.72,3.63,3.42,33,1.55,1.52,2.57,2.46,20,-0.50,2.07,2.03,1.89,1.84,2.36,3.75,3.03
27,E1,15/08/17,Cardiff,Sheffield United,2,0,H,1,0,H,L Mason,19,13,6,4,11,8,7,6,2,1,0,0,1.91,3.60,4.50,1.83,3.40,4.40,1.85,3.35,4.20,1.91,3.50,4.60,1.89,3.64,4.62,1.85,3.50,4.33,1.90,3.60,4.60,39,2.00,1.88,3.64,3.46,4.62,4.29,35,2.17,2.12,1.79,1.71,20,-0.50,1.95,1.86,2.07,2.00,1.90,3.51,4.78
28,E1,15/08/17,Derby,Preston,1,0,H,0,0,D,G Eltringham,15,9,5,4,14,15,4,4,2,3,0,0,2.00,3.40,4.33,1.91,3.40,4.00,1.95,3.25,3.85,2.00,3.40,4.20,1.99,3.52,4.29,2.00,3.25,4.00,2.00,3.40,4.20,39,2.05,1.98,3.52,3.35,4.33,4.00,37,2.19,2.12,1.78,1.71,20,-0.50,2.00,1.97,1.95,1.90,1.97,3.55,4.32
29,E1,15/08/17,Hull,Wolves,2,3,A,1,2,A,J Simpson,11,8,4,4,11,8,4,4,2,4,0,0,2.65,3.25,2.90,2.50,3.20,2.80,2.55,3.05,2.80,2.62,3.20,2.90,2.63,3.26,3.00,2.60,3.10,2.88,2.60,3.25,3.00,39,2.70,2.58,3.30,3.16,3.00,2.86,35,2.31,2.25,1.69,1.63,19,0.00,1.85,1.82,2.09,2.05,2.71,3.17,2.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,E1,16/09/17,Hull,Sunderland,1,1,D,0,1,A,D England,20,9,7,3,13,10,11,2,2,5,0,0,2.10,3.50,3.80,1.87,3.50,4.00,2.00,3.35,3.60,2.10,3.30,3.50,2.06,3.44,4.02,2.10,3.20,3.75,2.10,3.50,3.80,36,2.15,2.05,3.50,3.34,4.02,3.66,34,2.04,1.97,1.87,1.82,14,-0.25,1.80,1.76,2.16,2.11,2.14,3.57,3.66
89,E1,16/09/17,Ipswich,Bolton,2,0,H,0,0,D,A Madley,13,16,5,3,15,11,6,8,1,3,0,0,2.00,3.60,4.00,2.00,3.30,3.70,2.00,3.35,3.50,2.00,3.40,3.60,2.11,3.51,3.75,1.95,3.50,3.80,2.05,3.60,3.70,36,2.11,2.03,3.60,3.43,4.00,3.61,34,2.04,1.97,1.89,1.81,14,-0.50,2.11,2.07,1.87,1.80,2.02,3.45,4.23
90,E1,16/09/17,Middlesbrough,QPR,3,2,H,1,1,D,D Bond,16,10,8,2,17,14,6,1,4,4,0,0,1.73,3.80,5.50,1.72,3.80,4.50,1.65,3.60,4.95,1.73,3.60,4.80,1.71,3.79,5.66,1.70,3.50,5.50,1.73,3.80,5.50,36,1.75,1.70,3.90,3.63,5.66,5.10,34,2.04,1.97,1.91,1.82,13,-0.75,1.95,1.91,2.00,1.94,1.71,3.84,5.71
91,E1,16/09/17,Millwall,Leeds,1,0,H,0,0,D,T Robinson,20,1,6,0,12,13,14,2,1,3,0,0,3.00,3.30,2.55,2.80,3.20,2.50,2.80,3.10,2.50,2.80,3.10,2.55,3.00,3.15,2.67,2.90,3.20,2.50,2.90,3.25,2.63,36,3.00,2.86,3.30,3.14,2.70,2.54,33,2.23,2.15,1.74,1.68,13,0.00,2.09,2.03,1.87,1.83,3.27,3.31,2.43
92,E1,16/09/17,Nott'm Forest,Wolves,1,2,A,0,0,D,G Eltringham,7,11,6,6,4,15,1,4,2,2,0,0,3.60,3.30,2.25,3.40,3.10,2.20,3.30,3.20,2.15,3.30,3.20,2.20,3.86,3.25,2.18,3.30,3.20,2.25,3.50,3.30,2.25,36,3.86,3.41,3.40,3.22,2.25,2.19,33,2.12,2.03,1.84,1.76,13,0.25,2.03,1.98,1.92,1.87,3.48,3.38,2.29
93,E1,16/09/17,Sheffield United,Norwich,0,1,A,0,1,A,S Duncan,17,11,4,3,7,14,6,2,2,5,0,0,2.50,3.50,2.90,2.35,3.40,2.85,2.45,3.30,2.70,2.45,3.40,2.75,2.46,3.50,3.00,2.50,3.20,2.90,2.50,3.40,2.90,36,2.50,2.43,3.50,3.38,3.00,2.84,33,1.90,1.81,2.05,1.97,13,-0.25,2.19,2.10,1.81,1.77,2.67,3.52,2.76
94,E1,23/09/17,Aston Villa,Nott'm Forest,2,1,H,1,0,H,T Robinson,11,13,4,5,14,9,3,4,1,3,0,0,1.75,3.70,5.50,1.72,3.40,5.25,1.70,3.60,4.75,1.70,3.60,4.80,1.77,3.70,5.31,1.73,3.50,5.00,1.75,3.70,5.25,40,1.77,1.73,3.75,3.57,5.50,5.04,39,2.01,1.92,1.96,1.87,17,-0.75,1.99,1.92,1.98,1.93,1.65,3.94,6.18
95,E1,23/09/17,Bolton,Brentford,0,3,A,0,1,A,D England,10,22,3,10,22,13,5,6,2,1,0,0,3.75,3.75,2.05,3.50,3.50,2.00,3.60,3.55,1.95,3.60,3.50,2.00,3.79,3.72,2.03,3.60,3.50,2.00,3.75,3.75,2.05,40,3.83,3.61,3.75,3.58,2.05,1.99,38,1.82,1.74,2.16,2.07,17,0.50,1.90,1.86,2.03,1.99,3.71,3.75,2.07
96,E1,23/09/17,Derby,Birmingham,1,1,D,0,0,D,R East,10,10,4,2,14,10,4,6,1,1,0,0,1.80,3.75,5.00,1.75,3.70,4.40,1.75,3.50,4.45,1.75,3.50,4.60,1.78,3.79,5.05,1.80,3.30,5.00,1.83,3.75,4.80,40,1.83,1.77,3.80,3.58,5.05,4.66,39,2.02,1.94,1.93,1.84,17,-0.75,2.07,2.01,1.89,1.84,1.79,3.75,5.13
97,E1,23/09/17,Fulham,Middlesbrough,1,1,D,0,0,D,O Langford,10,14,4,3,16,8,6,3,2,1,0,0,2.38,3.40,3.20,2.30,3.40,2.95,2.25,3.30,3.00,2.25,3.25,3.10,2.32,3.37,3.36,2.30,3.20,3.20,2.30,3.40,3.30,40,2.38,2.29,3.45,3.29,3.36,3.14,39,2.06,1.96,1.91,1.83,17,-0.25,2.01,1.96,1.95,1.89,2.30,3.39,3.45
98,E1,23/09/17,Leeds,Ipswich,3,2,H,2,1,H,G Eltringham,9,14,2,3,11,11,6,12,1,2,0,0,1.62,3.90,6.50,1.57,3.70,6.25,1.55,3.75,5.75,1.57,3.75,6.00,1.63,3.89,6.49,1.62,3.80,5.50,1.62,3.90,6.50,40,1.65,1.60,4.00,3.74,6.50,6.00,39,2.05,1.99,1.90,1.80,19,-1.00,2.15,2.07,1.84,1.79,1.65,3.94,6.21
99,E1,23/09/17,Norwich,Bristol City,0,0,D,0,0,D,K Stroud,15,10,1,3,15,19,3,6,1,1,0,0,1.95,3.80,4.00,1.91,3.60,3.70,1.90,3.65,3.55,1.95,3.60,3.50,2.00,3.78,3.83,1.95,3.50,3.80,2.00,3.90,3.70,40,2.00,1.94,3.90,3.66,4.00,3.68,34,1.67,1.60,2.41,2.28,18,-0.50,2.00,1.95,1.95,1.91,2.22,3.64,3.39
100,E1,23/09/17,Preston,Millwall,0,0,D,0,0,D,D Bond,12,10,2,1,18,16,7,6,3,1,0,0,2.05,3.50,4.00,1.95,3.40,3.75,2.00,3.35,3.60,2.00,3.40,3.75,2.00,3.59,4.06,2.05,3.30,3.75,2.05,3.50,3.90,40,2.05,2.00,3.60,3.41,4.06,3.76,39,2.03,1.96,1.93,1.82,18,-0.50,2.05,2.00,1.92,1.86,2.06,3.65,3.83
101,E1,23/09/17,QPR,Burton,0,0,D,0,0,D,A Madley,13,5,4,1,17,11,8,6,0,0,0,0,1.75,3.75,5.25,1.67,3.70,5.00,1.70,3.70,4.65,1.70,3.75,4.80,1.71,3.95,5.29,1.80,3.30,5.00,1.75,4.00,5.00,40,1.80,1.71,4.00,3.75,5.29,4.85,39,1.82,1.77,2.14,2.03,17,-0.75,1.95,1.90,2.01,1.96,1.91,3.58,4.63
102,E1,23/09/17,Reading,Hull,1,1,D,0,1,A,S Martin,13,5,3,2,11,6,9,1,0,0,0,0,2.50,3.40,3.00,2.30,3.30,3.00,2.35,3.25,2.85,2.40,3.25,2.90,2.47,3.53,2.96,2.40,3.30,2.90,2.50,3.40,3.00,40,2.50,2.40,3.53,3.33,3.10,2.92,39,2.05,1.94,1.93,1.84,18,-0.25,2.13,2.09,1.82,1.78,2.54,3.56,2.90
103,E1,23/09/17,Sunderland,Cardiff,1,2,A,0,1,A,P Bankes,11,20,4,7,18,19,1,8,3,3,0,0,3.00,3.30,2.60,2.85,3.10,2.55,2.85,3.10,2.45,2.87,3.10,2.50,3.08,3.03,2.70,2.80,3.10,2.62,2.90,3.30,2.63,40,3.08,2.90,3.30,3.11,2.70,2.54,38,2.31,2.16,1.76,1.67,16,0.00,2.09,2.05,1.85,1.81,2.84,3.27,2.76
104,E1,23/09/17,Wolves,Barnsley,2,1,H,0,0,D,J Simpson,14,13,4,3,15,4,5,8,3,1,0,0,1.44,4.75,8.00,1.40,4.50,7.25,1.40,4.50,7.00,1.44,4.50,7.50,1.43,4.75,8.55,1.40,4.50,8.00,1.45,4.75,8.00,40,1.45,1.42,4.80,4.55,8.55,7.55,34,1.71,1.64,2.27,2.20,17,-1.25,1.99,1.93,1.97,1.92,1.42,5.04,8.39
105,E1,24/09/17,Sheffield Weds,Sheffield United,2,4,A,1,2,A,S Hooper,12,12,2,7,13,18,9,7,1,2,0,0,2.10,3.30,4.10,2.10,3.10,3.70,2.00,3.20,3.70,2.05,3.10,3.80,2.08,3.24,4.25,2.10,3.00,4.00,2.10,3.30,4.00,39,2.15,2.06,3.30,3.18,4.25,3.85,34,2.41,2.29,1.68,1.60,17,-0.50,2.13,2.06,1.85,1.81,1.94,3.36,4.69
106,E1,26/09/17,Barnsley,QPR,1,1,D,1,0,H,G Eltringham,9,14,3,4,15,8,2,6,1,2,0,0,2.63,3.60,2.70,2.45,3.50,2.65,2.45,3.40,2.65,2.50,3.40,2.65,2.62,3.51,2.79,2.50,3.40,2.75,2.60,3.60,2.75,39,2.63,2.54,3.60,3.45,2.80,2.68,37,1.78,1.72,2.19,2.09,17,-0.25,2.27,2.21,1.74,1.70,2.74,3.63,2.63
107,E1,26/09/17,Brentford,Derby,1,1,D,0,1,A,A Davies,14,3,2,2,7,12,11,0,3,5,0,0,2.25,3.70,3.20,2.25,3.40,3.00,2.20,3.40,3.00,2.25,3.50,3.00,2.29,3.62,3.21,2.25,3.50,3.00,2.30,3.70,3.10,39,2.36,2.25,3.75,3.51,3.25,3.07,35,1.73,1.67,2.28,2.17,18,-0.25,2.01,1.97,1.95,1.90,2.30,3.73,3.15
108,E1,26/09/17,Bristol City,Bolton,2,0,H,1,0,H,T Harrington,20,5,8,3,8,21,9,1,2,2,0,1,1.50,4.60,7.00,1.48,4.25,6.25,1.45,4.20,6.25,1.50,4.20,6.50,1.51,4.55,7.08,1.44,4.20,7.50,1.50,4.60,7.00,39,1.53,1.48,4.66,4.35,7.50,6.60,36,1.76,1.69,2.22,2.13,19,-1.00,1.86,1.81,2.11,2.04,1.47,4.81,7.70
109,E1,26/09/17,Burton,Aston Villa,0,4,A,0,3,A,J Moss,10,10,2,5,8,12,4,4,0,0,0,0,4.33,3.50,1.95,3.90,3.50,1.90,3.95,3.35,1.90,4.20,3.30,1.91,4.32,3.55,1.95,4.20,3.40,1.91,4.30,3.50,1.95,39,4.40,4.08,3.60,3.43,1.96,1.92,36,2.16,2.06,1.81,1.74,17,0.50,1.97,1.93,1.97,1.93,4.37,3.55,1.96
110,E1,26/09/17,Cardiff,Leeds,3,1,H,2,0,H,K Friend,16,8,6,3,16,15,2,0,0,1,0,1,2.05,3.50,3.90,2.05,3.40,3.50,2.00,3.35,3.55,2.00,3.30,3.70,2.05,3.54,3.93,2.10,3.30,3.50,2.05,3.50,3.80,39,2.10,2.04,3.60,3.41,3.93,3.68,36,2.10,1.99,1.91,1.81,18,-0.50,2.06,2.03,1.88,1.84,2.14,3.53,3.70
111,E1,26/09/17,Hull,Preston,1,2,A,0,1,A,J Linington,12,15,3,7,21,18,6,2,4,2,0,0,2.30,3.50,3.30,2.15,3.40,3.20,2.20,3.25,3.15,2.25,3.25,3.25,2.25,3.46,3.42,2.25,3.30,3.20,2.25,3.50,3.40,39,2.35,2.23,3.50,3.34,3.42,3.25,37,2.07,1.99,1.88,1.80,18,-0.25,1.97,1.92,1.98,1.94,2.41,3.38,3.22
112,E1,26/09/17,Ipswich,Sunderland,5,2,H,2,1,H,T Robinson,19,14,11,6,12,10,5,4,1,2,0,0,2.45,3.25,3.20,2.40,3.10,3.00,2.35,3.15,2.95,2.37,3.10,3.00,2.48,3.21,3.22,2.40,3.20,3.00,2.45,3.30,3.13,39,2.50,2.41,3.30,3.19,3.22,3.04,37,2.20,2.08,1.80,1.73,18,-0.25,2.11,2.05,1.85,1.82,2.64,3.27,2.98
113,E1,26/09/17,Middlesbrough,Norwich,0,1,A,0,1,A,J Simpson,21,5,5,2,8,16,13,1,1,4,0,0,1.95,3.60,4.20,1.91,3.30,4.10,1.90,3.40,3.85,1.95,3.40,4.00,1.94,3.66,4.21,1.91,3.50,4.00,1.95,3.60,4.20,39,2.00,1.93,3.66,3.46,4.21,4.02,37,2.09,2.00,1.86,1.79,18,-0.50,1.97,1.92,1.99,1.94,1.94,3.68,4.28
114,E1,26/09/17,Millwall,Reading,2,1,H,0,0,D,A Madley,6,8,4,3,12,10,3,4,1,0,0,0,2.10,3.40,3.90,2.00,3.25,3.75,2.00,3.25,3.60,2.10,3.25,3.60,2.13,3.47,3.75,2.05,3.25,3.75,2.15,3.40,3.80,39,2.15,2.06,3.47,3.32,4.00,3.69,36,2.15,2.07,1.81,1.74,18,-0.50,2.13,2.08,1.83,1.79,2.19,3.40,3.71
115,E1,26/09/17,Nott'm Forest,Fulham,1,3,A,1,1,D,S Duncan,20,16,4,7,11,9,3,3,2,0,0,0,3.20,3.60,2.30,3.10,3.30,2.25,3.05,3.35,2.20,3.00,3.50,2.20,3.28,3.45,2.32,3.10,3.50,2.20,3.20,3.60,2.25,39,3.30,3.12,3.60,3.43,2.32,2.24,35,1.73,1.65,2.28,2.20,17,0.25,1.96,1.92,2.00,1.94,3.24,3.80,2.23
116,E1,27/09/17,Birmingham,Sheffield Weds,1,0,H,0,0,D,S Martin,9,17,3,3,6,11,4,10,0,0,0,0,2.90,3.30,2.63,2.85,3.10,2.50,2.85,3.10,2.50,2.87,3.00,2.55,2.92,3.25,2.67,2.88,3.20,2.50,2.90,3.30,2.63,39,2.95,2.85,3.30,3.13,2.67,2.54,32,2.40,2.31,1.62,1.58,15,0.00,2.08,2.03,1.87,1.83,2.72,3.31,2.86
117,E1,27/09/17,Sheffield United,Wolves,2,0,H,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.00,3.30,2.55,2.85,3.10,2.50,2.75,3.15,2.50,2.87,3.10,2.55,2.96,3.29,2.61,2.80,3.30,2.50,3.00,3.30,2.60,39,3.00,2.84,3.40,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35

In [4]:
list_club_names = raw_data_14.HomeTeam.unique().tolist() + raw_data_14.AwayTeam.unique().tolist()
list_club_names = sorted(list(set(list_club_names)))
print(list_club_names)

['Aston Villa', 'Barnsley', 'Birmingham', 'Bolton', 'Brentford', 'Bristol City', 'Burton', 'Cardiff', 'Derby', 'Fulham', 'Hull', 'Ipswich', 'Leeds', 'Middlesbrough', 'Millwall', 'Norwich', "Nott'm Forest", 'Preston', 'QPR', 'Reading', 'Sheffield United', 'Sheffield Weds', 'Sunderland', 'Wolves']

In [5]:
def convert_team_name_standing_to_CSV_name(standings_team_name):
    dic_convert_name = {'Aston Villa'         : 'Aston Villa',
                        'Barnsley'            : 'Barnsley',
                        'Birmingham'          : 'Birmingham', 
                        'Blackburn Rovers'    : 'Blackburn', 
                        'Blackpool'           : 'Blackpool', 
                        'Bolton Wanderers'    : 'Bolton', 
                        'Bournemouth'         : 'Bournemouth', 
                        'Brentford'           : 'Brentford', 
                        'Brighton'            : 'Brighton', 
                        'Bristol City'        : 'Bristol City', 
                        'Burnley'             : 'Burnley', 
                        'Burton Albion'       : 'Burton', 
                        'Cardiff'             : 'Cardiff', 
                        'Charlton'            : 'Charlton', 
                        'Colchester United'   : 'Colchester', 
                        'Coventry City'       : 'Coventry', 
                        'Crewe'               : 'Crewe', 
                        'Crystal Palace'      : 'Crystal Palace', 
                        'Derby County'        : 'Derby', 
                        'Doncaster Rovers'    : 'Doncaster', 
                        'Fulham'              : 'Fulham', 
                        'Gillingham'          : 'Gillingham', 
                        'Huddersfield Town'   : 'Huddersfield', 
                        'Hull City'           : 'Hull', 
                        'Ipswich Town'        : 'Ipswich', 
                        'Leeds'               : 'Leeds', 
                        'Leicester City'      : 'Leicester', 
                        'Luton Town'          : 'Luton', 
                        'MK Dons'             : 'Milton Keynes Dons', 
                        'Middlesbrough'       : 'Middlesbrough', 
                        'Millwall'            : 'Millwall', 
                        'Newcastle'           : 'Newcastle', 
                        'Norwich'             : 'Norwich', 
                        'Nottingham Forest'   : "Nott'm Forest", 
                        'Peterborough United' : 'Peterboro', 
                        'Plymouth Argyle'     : 'Plymouth', 
                        'Portsmouth'          : 'Portsmouth', 
                        'Preston'             : 'Preston', 
                        'QPR'                 : 'QPR', 
                        'Reading'             : 'Reading', 
                        'Rotherham'           : 'Rotherham', 
                        'Scunthorpe United'   : 'Scunthorpe', 
                        'Sheffield United'    : 'Sheffield United', 
                        'Sheffield Wednesday' : 'Sheffield Weds', 
                        'Southampton'         : 'Southampton', 
                        'Southend United'     : 'Southend',
                        'Stoke City'          : 'Stoke',
                        'Sunderland'          : 'Sunderland', 
                        'Swansea City'        : 'Swansea', 
                        'Watford'             : 'Watford', 
                        'West Bromwich'       : 'West Brom', 
                        'West Ham'            : 'West Ham', 
                        'Wigan'               : 'Wigan', 
                        'Wolves'              : 'Wolves', 
                        'Yeovil'              : 'Yeovil'}
    
    # TODO: Colocar try catch
    CSV_name = dic_convert_name[standings_team_name]
    return CSV_name

str_csv_team_name_tmp = convert_team_name_standing_to_CSV_name('Hull City') #  -> 'Hull' 
print("Hull City -> ", str_csv_team_name_tmp)

Hull City ->  Hull

In [6]:
from pandas import ExcelWriter
from pandas import ExcelFile

loc_FLC_Standings = "./FLC_Standings/"

def get_last_year_team_name_position(dic_standings, team_name, year, empty_value = 22):
    key_str = str(year) + team_name.upper()
    if key_str in dic_standings:
        return dic_standings[key_str]
    else:
        return empty_value

def dic_union_2(dict1, dict2):
    return dict(list(dict1.items()) + list(dict2.items()))

def get_file_standings(filename, year, dic_standings, set_all_team_names):
    df = pd.read_excel(loc_FLC_Standings + filename, sheetname='Folha1') # sheetname='Sheet1')

    list_team_positions = df[df.columns[2]]
    #print(list_team_positions)
    list_team_positions = list_team_positions.tolist()
    #print(list_team_positions)
    
    for i, standings_team_name in enumerate(list_team_positions):
        print(i, standings_team_name)
        csv_team_name = convert_team_name_standing_to_CSV_name(standings_team_name)
        dic_standings[str(year) + csv_team_name.upper()] = i + 1
        set_all_team_names.add(csv_team_name)
        
    #print("Column headings:")
    #print(df.columns)    

    return dic_standings, set_all_team_names


def read_all_standings():
    standings = {}
    all_team_names = set()
    
    standings, all_team_names = get_file_standings('FLC_2004_2005.xlsx', 2004, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2005_2006.xlsx', 2005, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2006_2007.xlsx', 2006, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2007_2008.xlsx', 2007, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2008_2009.xlsx', 2008, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2009_2010.xlsx', 2009, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2010_2011.xlsx', 2010, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2011_2012.xlsx', 2011, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2012_2013.xlsx', 2012, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2013_2014.xlsx', 2013, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2014_2015.xlsx', 2014, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2015_2016.xlsx', 2015, standings, all_team_names)    
    standings, all_team_names = get_file_standings('FLC_2016_2017.xlsx', 2016, standings, all_team_names)    
            
    return standings, all_team_names

standings, all_team_names = read_all_standings()

sorted_all_team_names = sorted(list(all_team_names)) #.sort()

print("sorted_all_teams_names: ")
print(sorted_all_team_names)

print()

print("last_year_team_position: ", get_last_year_team_name_position(standings, "Wolves", 2016))

# print("dic: ", standings)

0 Sunderland
1 Wigan
2 Ipswich Town
3 Derby County
4 Preston
5 West Ham
6 Reading
7 Sheffield United
8 Wolves
9 Millwall
10 QPR
11 Stoke City
12 Burnley
13 Leeds
14 Leicester City
15 Cardiff
16 Plymouth Argyle
17 Watford
18 Coventry City
19 Brighton
20 Crewe
21 Gillingham
22 Nottingham Forest
23 Rotherham
0 Reading
1 Sheffield United
2 Watford
3 Preston
4 Leeds
5 Crystal Palace
6 Wolves
7 Coventry City
8 Norwich
9 Luton Town
10 Cardiff
11 Southampton
12 Stoke City
13 Plymouth Argyle
14 Ipswich Town
15 Leicester City
16 Burnley
17 Hull City
18 Sheffield Wednesday
19 Derby County
20 QPR
21 Crewe
22 Millwall
23 Brighton
0 Sunderland
1 Birmingham
2 Derby County
3 West Bromwich
4 Wolves
5 Southampton
6 Preston
7 Stoke City
8 Sheffield Wednesday
9 Colchester United
10 Plymouth Argyle
11 Crystal Palace
12 Cardiff
13 Ipswich Town
14 Burnley
15 Norwich
16 Coventry City
17 QPR
18 Leicester City
19 Barnsley
20 Hull City
21 Southend United
22 Luton Town
23 Leeds
0 West Bromwich
1 Stoke City
2 Hull City
3 Bristol City
4 Crystal Palace
5 Watford
6 Wolves
7 Ipswich Town
8 Sheffield United
9 Plymouth Argyle
10 Charlton
11 Cardiff
12 Burnley
13 QPR
14 Preston
15 Sheffield Wednesday
16 Norwich
17 Barnsley
18 Blackpool
19 Southampton
20 Coventry City
21 Leicester City
22 Scunthorpe United
23 Colchester United
0 Wolves
1 Birmingham
2 Sheffield United
3 Reading
4 Burnley
5 Preston
6 Cardiff
7 Swansea City
8 Ipswich Town
9 Bristol City
10 QPR
11 Sheffield Wednesday
12 Watford
13 Doncaster Rovers
14 Crystal Palace
15 Blackpool
16 Coventry City
17 Derby County
18 Nottingham Forest
19 Barnsley
20 Plymouth Argyle
21 Norwich
22 Southampton
23 Charlton
0 Newcastle
1 West Bromwich
2 Nottingham Forest
3 Cardiff
4 Leicester City
5 Blackpool
6 Swansea City
7 Sheffield United
8 Reading
9 Bristol City
10 Middlesbrough
11 Doncaster Rovers
12 QPR
13 Derby County
14 Ipswich Town
15 Watford
16 Preston
17 Barnsley
18 Coventry City
19 Scunthorpe United
20 Crystal Palace
21 Sheffield Wednesday
22 Plymouth Argyle
23 Peterborough United
0 QPR
1 Norwich
2 Swansea City
3 Cardiff
4 Reading
5 Nottingham Forest
6 Leeds
7 Burnley
8 Millwall
9 Leicester City
10 Hull City
11 Middlesbrough
12 Ipswich Town
13 Watford
14 Bristol City
15 Portsmouth
16 Barnsley
17 Coventry City
18 Derby County
19 Crystal Palace
20 Doncaster Rovers
21 Preston
22 Sheffield United
23 Scunthorpe United
0 Reading
1 Southampton
2 West Ham
3 Birmingham
4 Blackpool
5 Cardiff
6 Middlesbrough
7 Hull City
8 Leicester City
9 Brighton
10 Watford
11 Derby County
12 Burnley
13 Leeds
14 Ipswich Town
15 Millwall
16 Crystal Palace
17 Peterborough United
18 Nottingham Forest
19 Bristol City
20 Barnsley
21 Portsmouth
22 Coventry City
23 Doncaster Rovers
0 Cardiff
1 Hull City
2 Watford
3 Brighton
4 Crystal Palace
5 Leicester City
6 Bolton Wanderers
7 Nottingham Forest
8 Charlton
9 Derby County
10 Burnley
11 Birmingham
12 Leeds
13 Ipswich Town
14 Blackpool
15 Middlesbrough
16 Blackburn Rovers
17 Sheffield Wednesday
18 Huddersfield Town
19 Millwall
20 Barnsley
21 Peterborough United
22 Wolves
23 Bristol City
0 Leicester City
1 Burnley
2 Derby County
3 QPR
4 Wigan
5 Brighton
6 Reading
7 Blackburn Rovers
8 Ipswich Town
9 Bournemouth
10 Nottingham Forest
11 Middlesbrough
12 Watford
13 Bolton Wanderers
14 Leeds
15 Sheffield Wednesday
16 Huddersfield Town
17 Charlton
18 Millwall
19 Blackpool
20 Birmingham
21 Doncaster Rovers
22 Barnsley
23 Yeovil
0 Bournemouth
1 Watford
2 Norwich
3 Middlesbrough
4 Brentford
5 Ipswich Town
6 Wolves
7 Derby County
8 Blackburn Rovers
9 Birmingham
10 Cardiff
11 Charlton
12 Sheffield Wednesday
13 Nottingham Forest
14 Leeds
15 Huddersfield Town
16 Fulham
17 Bolton Wanderers
18 Reading
19 Brighton
20 Rotherham
21 Millwall
22 Wigan
23 Blackpool
0 Burnley
1 Middlesbrough
2 Brighton
3 Hull City
4 Derby County
5 Sheffield Wednesday
6 Ipswich Town
7 Cardiff
8 Brentford
9 Birmingham
10 Preston
11 QPR
12 Leeds
13 Wolves
14 Blackburn Rovers
15 Nottingham Forest
16 Reading
17 Bristol City
18 Huddersfield Town
19 Fulham
20 Rotherham
21 Charlton
22 MK Dons
23 Bolton Wanderers
0 Newcastle
1 Brighton
2 Reading
3 Sheffield Wednesday
4 Huddersfield Town
5 Fulham
6 Leeds
7 Norwich
8 Derby County
9 Brentford
10 Preston
11 Cardiff
12 Aston Villa
13 Barnsley
14 Wolves
15 Ipswich Town
16 Bristol City
17 QPR
18 Birmingham
19 Burton Albion
20 Nottingham Forest
21 Blackburn Rovers
22 Wigan
23 Rotherham
sorted_all_teams_names:
['Aston Villa', 'Barnsley', 'Birmingham', 'Blackburn', 'Blackpool', 'Bolton', 'Bournemouth', 'Brentford', 'Brighton', 'Bristol City', 'Burnley', 'Burton', 'Cardiff', 'Charlton', 'Colchester', 'Coventry', 'Crewe', 'Crystal Palace', 'Derby', 'Doncaster', 'Fulham', 'Gillingham', 'Huddersfield', 'Hull', 'Ipswich', 'Leeds', 'Leicester', 'Luton', 'Middlesbrough', 'Millwall', 'Milton Keynes Dons', 'Newcastle', 'Norwich', "Nott'm Forest", 'Peterboro', 'Plymouth', 'Portsmouth', 'Preston', 'QPR', 'Reading', 'Rotherham', 'Scunthorpe', 'Sheffield United', 'Sheffield Weds', 'Southampton', 'Southend', 'Stoke', 'Sunderland', 'Swansea', 'Watford', 'West Brom', 'West Ham', 'Wigan', 'Wolves', 'Yeovil']

last_year_team_position:  15

In [7]:
# Esta celula foi adicionada por mim e não está a funcionar pois não me está a permitir criar um registo
# novo por copia de um exitente ligueiramente diferente do original e não sei o porquÊ!

#display(raw_data_18.tail())

#raw_data_16 = raw_data_16[:-1] #drop bottom 1 
#display(raw_data_16.tail())

import datetime


def add_new_game_to_predict(date_str, homeTeam, awayTeam):     # date_str = '15/09/17'
    
    global raw_data_14
    
    # Muito importante, converte entre o nome do Google e o nome do ficheiro CSV.
    homeTeam = convert_team_name_standing_to_CSV_name(homeTeam)
    awayTeam = convert_team_name_standing_to_CSV_name(awayTeam)
    
    
    #  Add line to the end.
    last_index = raw_data_14.tail(1).index[0]
    raw_data_14 = raw_data_14.append(raw_data_14.iloc[last_index], ignore_index=True )


    # É H de Home o valor real, deste ultimo caso de teste.
    gameDate = datetime.datetime.strptime(date_str, '%d/%m/%y').date(  ).__format__('%d/%m/%y')

    last_index = raw_data_14.tail(1).index[0]
    #print("last_index: ", last_index)

    # Set the date
    raw_data_14.set_value(index=last_index, col=1, value=gameDate, takeable=True)  # Date
    
    # Set the teams names of one new game.
    raw_data_14.set_value(index=last_index, col=2, value=homeTeam, takeable=True)  # HomeTeam
    raw_data_14.set_value(index=last_index, col=3, value=awayTeam, takeable=True)  # AwayTeam

    # Clear the goals and result.
    raw_data_14.set_value(index=last_index, col=4, value=0, takeable=True)     # FTHG  [Full Time Home Goals]
    raw_data_14.set_value(index=last_index, col=5, value=0, takeable=True)     # FTAG  [Full Time Away Goals]
    raw_data_14.set_value(index=last_index, col=6, value="", takeable=True)    # FTR   [Full Time Result]


    
#[ 'Arsenal',
#  'Bournemouth',
#  'Brighton',
#  'Burnley',
#  'Chelsea',
#  'Crystal Palace',
#  'Everton',
#  'Huddersfield',
#  'Leicester',
#  'Liverpool',
#  'Man City',
#  'Man United',
#  'Newcastle',
#  'Southampton',
#  'Stoke',
#  'Swansea',
#  'Tottenham',
#  'Watford',
#  'West Brom',
#  'West Ham'   ]


display(raw_data_14.tail())

###############################################
###############################################

# Sexta
# 29/09/17 QPR 19:45 Fulham
add_new_game_to_predict('29/09/17', 'QPR', 'Fulham')

# Sábado
# 30/09/17 Preston 15:00 Sunderland
add_new_game_to_predict('30/09/17', 'Preston', 'Sunderland' ) 
                        
# 30/09/17 Aston Villa 15:00 Bolton Wanderers
add_new_game_to_predict('30/09/17', 'Aston Villa', 'Bolton Wanderers')

# 30/09/17 Middlesbrough 15:00 Brentford
add_new_game_to_predict('30/09/17', 'Middlesbrough', 'Brentford')

# 30/09/17 Burton Albion 15:00 Wolves
add_new_game_to_predict('30/09/17', 'Burton Albion', 'Wolves')

# 30/09/17 Ipswich Town 15:00 Bristol City
add_new_game_to_predict('30/09/17', 'Ipswich Town', 'Bristol City')

# 30/09/17 Millwall 15:00 Barnsley
add_new_game_to_predict('30/09/17', 'Millwall', 'Barnsley' )

# 30/09/17 Nottingham Forest 15:00 Sheffield United
add_new_game_to_predict('30/09/17', 'Nottingham Forest', 'Sheffield United')

# 30/09/17 Hull City 15:00 Birmingham
add_new_game_to_predict('30/09/17', 'Hull City', 'Birmingham' )

# 30/09/17 Cardiff 15:00 Derby County
add_new_game_to_predict('30/09/17', 'Cardiff', 'Derby County')

# 30/09/17 Reading 17:30 Norwich
add_new_game_to_predict('30/09/17', 'Reading', 'Norwich')

# Domingo
# 1/10/17 Sheffield Wednesday 12:15 Leeds
add_new_game_to_predict('1/10/17', 'Sheffield Wednesday', 'Leeds')



###############################################
###############################################
display(raw_data_14.tail(15))    
    
    
    
    
#raw_data_16 = raw_data_16.append({'Div'     : 'E0',
#                                  'Date'    : gameDate,
#                                  'HomeTeam':'Man City',
#                                  'AwayTeam':'Bournemouth',
#                                  'FTHG': 0,
#                                  'FTAG': 0,
#                                  'FTR': 'D',
#                                  'HTHG': 0,
#                                  'HTAG': 0,
#                                  'HTR': 'D',
#                                  'Referee': 'bola',
#                                  'HS': 0,
#                                  'AS': 0,
#                                  'HST': 0,
#                                  'AST': 0,
#                                  'HF': 0,
#                                  'AF': 0,
#                                  'HC': 0,
#                                  'AC': 0,
#                                  'HY': 0,
#                                  'AY': 0,
#                                  'HR': 0,
#                                  'AR': 0,
#                                  'B365H': 0,
#                                  'B365D': 0,
#                                  'B365A': 0,
#                                  'BWH': 0,
#                                  'BWD': 0,
#                                  'BWA': 0,
#                                  'IWH': 0,
#                                  'IWD': 0,
#                                  'IWA': 0,
#                                  'LBH': 0,
#                                  'LBD': 0,
#                                  'LBA': 0,
#                                  'PSH': 0,
#                                  'PSD': 0,
#                                  'PSA': 0,
#                                  'WHH': 0,
#                                  'WHD': 0,
#                                  'WHA': 0,
#                                  'VCH': 0,
#                                  'VCD': 0,
#                                  'VCA': 0,
#                                  'Bb1X2': 0,
#                                  'BbMxH': 0,
#                                  'BbAvH': 0,
#                                  'BbMxD': 0,
#                                  'BbAvD': 0,
#                                  'BbMxA': 0,
#                                  'BbAvA': 0,
#                                  'BbOU': 0,
#                                  'BbMx>2.5': 0,
#                                  'BbAv>2.5': 0,
#                                  'BbMx<2.5': 0,
#                                  'BbAv<2.5': 0,
#                                  'BbAH': 0,
#                                  'BbAHh': 0,
#                                  'BbMxAHH': 0,
#                                  'BbAvAHH': 0,
#                                  'BbMxAHA': 0, 
#                                  'BbAvAHA': 0   }, ignore_index=True)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
113,E1,26/09/17,Middlesbrough,Norwich,0,1,A,0,1,A,J Simpson,21,5,5,2,8,16,13,1,1,4,0,0,1.95,3.6,4.20,1.91,3.30,4.10,1.90,3.40,3.85,1.95,3.40,4.00,1.94,3.66,4.21,1.91,3.50,4.00,1.95,3.6,4.20,39,2.00,1.93,3.66,3.46,4.21,4.02,37,2.09,2.00,1.86,1.79,18,-0.50,1.97,1.92,1.99,1.94,1.94,3.68,4.28
114,E1,26/09/17,Millwall,Reading,2,1,H,0,0,D,A Madley,6,8,4,3,12,10,3,4,1,0,0,0,2.10,3.4,3.90,2.00,3.25,3.75,2.00,3.25,3.60,2.10,3.25,3.60,2.13,3.47,3.75,2.05,3.25,3.75,2.15,3.4,3.80,39,2.15,2.06,3.47,3.32,4.00,3.69,36,2.15,2.07,1.81,1.74,18,-0.50,2.13,2.08,1.83,1.79,2.19,3.40,3.71
115,E1,26/09/17,Nott'm Forest,Fulham,1,3,A,1,1,D,S Duncan,20,16,4,7,11,9,3,3,2,0,0,0,3.20,3.6,2.30,3.10,3.30,2.25,3.05,3.35,2.20,3.00,3.50,2.20,3.28,3.45,2.32,3.10,3.50,2.20,3.20,3.6,2.25,39,3.30,3.12,3.60,3.43,2.32,2.24,35,1.73,1.65,2.28,2.20,17,0.25,1.96,1.92,2.00,1.94,3.24,3.80,2.23
116,E1,27/09/17,Birmingham,Sheffield Weds,1,0,H,0,0,D,S Martin,9,17,3,3,6,11,4,10,0,0,0,0,2.90,3.3,2.63,2.85,3.10,2.50,2.85,3.10,2.50,2.87,3.00,2.55,2.92,3.25,2.67,2.88,3.20,2.50,2.90,3.3,2.63,39,2.95,2.85,3.30,3.13,2.67,2.54,32,2.40,2.31,1.62,1.58,15,0.00,2.08,2.03,1.87,1.83,2.72,3.31,2.86
117,E1,27/09/17,Sheffield United,Wolves,2,0,H,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.00,3.3,2.55,2.85,3.10,2.50,2.75,3.15,2.50,2.87,3.10,2.55,2.96,3.29,2.61,2.80,3.30,2.50,3.00,3.3,2.60,39,3.00,2.84,3.40,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,Bb1X2,BbMxH,BbAvH,BbMxD,BbAvD,BbMxA,BbAvA,BbOU,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
115,E1,26/09/17,Nott'm Forest,Fulham,1,3,A,1,1,D,S Duncan,20,16,4,7,11,9,3,3,2,0,0,0,3.2,3.6,2.30,3.10,3.3,2.25,3.05,3.35,2.2,3.00,3.5,2.20,3.28,3.45,2.32,3.10,3.5,2.2,3.2,3.6,2.25,39,3.30,3.12,3.6,3.43,2.32,2.24,35,1.73,1.65,2.28,2.20,17,0.25,1.96,1.92,2.00,1.94,3.24,3.80,2.23
116,E1,27/09/17,Birmingham,Sheffield Weds,1,0,H,0,0,D,S Martin,9,17,3,3,6,11,4,10,0,0,0,0,2.9,3.3,2.63,2.85,3.1,2.50,2.85,3.10,2.5,2.87,3.0,2.55,2.92,3.25,2.67,2.88,3.2,2.5,2.9,3.3,2.63,39,2.95,2.85,3.3,3.13,2.67,2.54,32,2.40,2.31,1.62,1.58,15,0.00,2.08,2.03,1.87,1.83,2.72,3.31,2.86
117,E1,27/09/17,Sheffield United,Wolves,2,0,H,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
118,E1,29/09/17,QPR,Fulham,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
119,E1,30/09/17,Preston,Sunderland,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
120,E1,30/09/17,Aston Villa,Bolton,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
121,E1,30/09/17,Middlesbrough,Brentford,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
122,E1,30/09/17,Burton,Wolves,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
123,E1,30/09/17,Ipswich,Bristol City,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
124,E1,30/09/17,Millwall,Barnsley,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
125,E1,30/09/17,Nott'm Forest,Sheffield United,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
126,E1,30/09/17,Hull,Birmingham,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
127,E1,30/09/17,Cardiff,Derby,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
128,E1,30/09/17,Reading,Norwich,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35
129,E1,01/10/17,Sheffield Weds,Leeds,0,0,,1,0,H,P Bankes,11,7,5,2,18,8,11,2,3,1,0,1,3.0,3.3,2.55,2.85,3.1,2.50,2.75,3.15,2.5,2.87,3.1,2.55,2.96,3.29,2.61,2.80,3.3,2.5,3.0,3.3,2.60,39,3.00,2.84,3.4,3.21,2.63,2.52,34,2.22,2.14,1.73,1.68,15,0.00,2.09,2.06,1.84,1.80,3.38,3.35,2.35

In [8]:
# Parse data as time 

def parse_date(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%y').date()
    

def parse_date_other(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%Y').date()

raw_data_1.Date = raw_data_1.Date.apply(parse_date)    
raw_data_2.Date = raw_data_2.Date.apply(parse_date)    
#raw_data_3.Date = raw_data_3.Date.apply(parse_date_other)         # The date format for this dataset is different  
raw_data_3.Date = raw_data_3.Date.apply(parse_date)
raw_data_4.Date = raw_data_4.Date.apply(parse_date)    
raw_data_5.Date = raw_data_5.Date.apply(parse_date)    
raw_data_6.Date = raw_data_6.Date.apply(parse_date)    
raw_data_7.Date = raw_data_7.Date.apply(parse_date)    
raw_data_8.Date = raw_data_8.Date.apply(parse_date)    
raw_data_9.Date = raw_data_9.Date.apply(parse_date)    
raw_data_10.Date = raw_data_10.Date.apply(parse_date)
raw_data_11.Date = raw_data_11.Date.apply(parse_date)
raw_data_12.Date = raw_data_12.Date.apply(parse_date)
raw_data_13.Date = raw_data_13.Date.apply(parse_date)
raw_data_14.Date = raw_data_14.Date.apply(parse_date)


#Gets all the statistics related to gameplay
                      
columns_req = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR']

playing_statistics_1 = raw_data_1[columns_req]                      
playing_statistics_2 = raw_data_2[columns_req]
playing_statistics_3 = raw_data_3[columns_req]
playing_statistics_4 = raw_data_4[columns_req]
playing_statistics_5 = raw_data_5[columns_req]
playing_statistics_6 = raw_data_6[columns_req]
playing_statistics_7 = raw_data_7[columns_req]
playing_statistics_8 = raw_data_8[columns_req]
playing_statistics_9 = raw_data_9[columns_req]
playing_statistics_10 = raw_data_10[columns_req]
playing_statistics_11 = raw_data_11[columns_req]   
playing_statistics_12 = raw_data_12[columns_req]
playing_statistics_13 = raw_data_13[columns_req]
playing_statistics_14 = raw_data_14[columns_req]

** GOALS SCORED AND CONCEDED AT THE END OF MATCHWEEK, ARRANGED BY TEAMS AND MATCHWEEK  **

In [9]:
# Gets the goals scored agg arranged by teams and matchweek

##############################

##  JNC Version.
def get_gss_jnc(playing_stat):
    
    # print("Start: ")
    # display(playing_stat)
    
    playing_stat['HTGS'] = 0
    playing_stat['ATGS'] = 0
    playing_stat['HTGC'] = 0
    playing_stat['ATGC'] = 0
    
    team_names_set = set()
    goals_dic = {}
    
    for i in range(0, len(playing_stat)):
        HTgoals_scored = 0
        ATgoals_scored = 0
        HTgoals_conceded = 0
        ATgoals_conceded = 0
        
        end_loop_home_flag = False
        end_loop_away_flag = False
        
        if (i > 0):
            homeTeam = playing_stat.iloc[i].HomeTeam
            awayTeam = playing_stat.iloc[i].AwayTeam
            
            team_names_set.add(homeTeam)
            team_names_set.add(awayTeam)
            
            # Loop from the previous line to the line 0 (zero).
            for j in range(i-1, -1, -1):
            # for j in range(0, i-1):
                # Generate the goals_dic keys for the line for the home and away teams.
                dic_key_homeTeam = homeTeam + str(j)
                dic_key_awayTeam = awayTeam + str(j)
                
                # HomeTeam: If isn't in goals_dic (in cache) calculate the value, accumulating goals. 
                if (end_loop_home_flag == False):
                    if (dic_key_homeTeam in goals_dic):
                        end_loop_home_flag = True
                        HTgoals_scored_tmp, HTgoals_conceded_tmp = goals_dic[dic_key_homeTeam]
                        HTgoals_scored += HTgoals_scored_tmp
                        HTgoals_conceded += HTgoals_conceded_tmp
                    else:
                        if (homeTeam == playing_stat.iloc[j].HomeTeam):
                            HTgoals_scored   += playing_stat.iloc[j].FTHG
                            HTgoals_conceded += playing_stat.iloc[j].FTAG
                        elif (homeTeam == playing_stat.iloc[j].AwayTeam):
                            HTgoals_scored   += playing_stat.iloc[j].FTAG
                            HTgoals_conceded += playing_stat.iloc[j].FTHG

                # AwayTeam: If isn't in goals_dic (in cache) calculate the value, accumulating goals.     
                if (end_loop_away_flag == False):
                    if (dic_key_awayTeam in goals_dic):
                        end_loop_away_flag = True
                        ATgoals_scored_tmp, ATgoals_conceded_tmp = goals_dic[dic_key_awayTeam]
                        ATgoals_scored += ATgoals_scored_tmp
                        ATgoals_conceded += ATgoals_conceded_tmp
                    else:
                        if (awayTeam == playing_stat.iloc[j].HomeTeam):
                            ATgoals_scored   += playing_stat.iloc[j].FTHG
                            ATgoals_conceded += playing_stat.iloc[j].FTAG
                        elif (awayTeam == playing_stat.iloc[j].AwayTeam):
                            ATgoals_scored   += playing_stat.iloc[j].FTAG
                            ATgoals_conceded += playing_stat.iloc[j].FTHG
                
                if ((end_loop_home_flag == True) and (end_loop_away_flag == True)):
                    # End's the loop.
                    break
                            
            # For the Home and Away Teams, add the goals of the current position - 1 to the goals_dic.
            dic_key_homeTeam = homeTeam + str(i-1)
            dic_key_awayTeam = awayTeam + str(i-1)
            goals_dic[dic_key_homeTeam] = (HTgoals_scored, HTgoals_conceded)
            goals_dic[dic_key_awayTeam] = (ATgoals_scored, ATgoals_conceded)        

        #print("HTgoals_scored :", HTgoals_scored)            
         
        # ERRO: Não atribui os valores às celulas do dataframe.    
        #playing_stat.iloc[i].HTGS = HTgoals_scored
        #playing_stat.iloc[i].ATGS = ATgoals_scored
        #playing_stat.iloc[i].HTGC = HTgoals_conceded
        #playing_stat.iloc[i].ATGC = ATgoals_conceded

        
        # Com esta solução já atribui o valor às ceclulas correctamente.
        #raw_data_16.set_value(index=379,col='FTR',value='D')
        playing_stat.set_value(index=i, col='HTGS', value=HTgoals_scored)
        playing_stat.set_value(index=i, col='ATGS', value=ATgoals_scored)
        playing_stat.set_value(index=i, col='HTGC', value=HTgoals_conceded)
        playing_stat.set_value(index=i, col='ATGC', value=ATgoals_conceded)
        
        
     
    # Debug
    #print("After: ")
    #display(playing_stat)
    
    
    return playing_stat, team_names_set

##############################

# jnc comentei os dados para debug.


# Apply to each dataset
get_gss = get_gss_jnc

# TODO: Descomentar, é só para debug para ser mais rapido.
playing_statistics_1, team_names_set_1 = get_gss(playing_statistics_1)

playing_statistics_2, team_names_set_2 = get_gss(playing_statistics_2)
playing_statistics_3, team_names_set_3 = get_gss(playing_statistics_3)
playing_statistics_4, team_names_set_4 = get_gss(playing_statistics_4)
playing_statistics_5, team_names_set_5 = get_gss(playing_statistics_5)
playing_statistics_6, team_names_set_6 = get_gss(playing_statistics_6)
playing_statistics_7, team_names_set_7 = get_gss(playing_statistics_7)
playing_statistics_8, team_names_set_8 = get_gss(playing_statistics_8)
playing_statistics_9, team_names_set_9 = get_gss(playing_statistics_9)
playing_statistics_10, team_names_set_10 = get_gss(playing_statistics_10)
playing_statistics_11, team_names_set_11 = get_gss(playing_statistics_11)
playing_statistics_12, team_names_set_12 = get_gss(playing_statistics_12)
playing_statistics_13, team_names_set_13 = get_gss(playing_statistics_13)
playing_statistics_14, team_names_set_14 = get_gss(playing_statistics_14)

C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

GET RESPECTIVE POINTS:

In [10]:
# This function is used by the new (jnc) and by the old code.
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0

############################
# JNC Version.

def get_cuml_points_jnc(match_res):
    # creates a dic of the points of each match by line.
    match_res_points = {}
    
    for team_line, matches in  match_res.items():
        accumulated_points = 0
        
        # calculate the points.
        for game_res in matches:
            accumulated_points += get_points(game_res)
            
        # Add the points to the line.
        match_res_points[team_line] = accumulated_points
    
    return match_res_points


def get_matchres_jnc(playing_stat, team_names_set):
    # NOTE: This line always have the resutls of the previous line.
    
    # Create a dictionary with team names with lines as keys.
    match_res = {}
    match_loc = {}
    match_line = {}
   
    # Set current line matches to 0 (zero).
    current_line_matches_res = {}
    current_line_matches_loc = {}
    current_line_matches_line = {}
    for team in team_names_set:
        current_line_matches_res[team] = []
        current_line_matches_loc[team] = []
        current_line_matches_line[team] = []
    
    for i in range(0, len(playing_stat)):
        homeTeam = playing_stat.iloc[i].HomeTeam
        awayTeam = playing_stat.iloc[i].AwayTeam
        
        # Add a copy of the matches the current results to the current line.
        for team in team_names_set:
            match_res[team + str(i)] = current_line_matches_res[team].copy()
            match_loc[team + str(i)] = current_line_matches_loc[team].copy()
            match_line[team + str(i)] = current_line_matches_line[team].copy()

            
        if playing_stat.iloc[i].FTR == 'H':
            current_line_matches_res[homeTeam].append('W')
            current_line_matches_res[awayTeam].append('L')
            
            current_line_matches_loc[homeTeam].append('H')
            current_line_matches_loc[awayTeam].append('A')
            
            current_line_matches_line[homeTeam].append(i)
            current_line_matches_line[awayTeam].append(i)
        
        elif playing_stat.iloc[i].FTR == 'A':
            current_line_matches_res[awayTeam].append('W')
            current_line_matches_res[homeTeam].append('L')
        
            current_line_matches_loc[homeTeam].append('H')
            current_line_matches_loc[awayTeam].append('A')
            
            current_line_matches_line[homeTeam].append(i)
            current_line_matches_line[awayTeam].append(i)
        
        elif playing_stat.iloc[i].FTR == 'D':
            current_line_matches_res[awayTeam].append('D')
            current_line_matches_res[homeTeam].append('D')
        
            current_line_matches_loc[homeTeam].append('H')
            current_line_matches_loc[awayTeam].append('A')
        
            current_line_matches_line[homeTeam].append(i)
            current_line_matches_line[awayTeam].append(i)
            
        else:
            # Caso em que não está preenchido!
            # Uitl para as linhas de resultado que se pretende prever.
            pass

    return match_res, match_loc, match_line


## JNC Version
def get_agg_points_jnc(playing_stat, team_names_set):
    
    # print("Start: ")
    # display(playing_stat)
    
    match_res, match_loc, match_line = get_matchres_jnc(playing_stat, team_names_set)
    cum_pts   = get_cuml_points_jnc(match_res)
    
    # Creates the 2 columns with the values 0 (zero).
    playing_stat['HTP'] = 0
    playing_stat['ATP'] = 0
        
    for i in range(0, len(playing_stat)):
        homeTeam = playing_stat.iloc[i].HomeTeam
        awayTeam = playing_stat.iloc[i].AwayTeam
           
        # Generate the goals_dic keys for the line for the home and away teams.
        dic_key_homeTeam = homeTeam + str(i)
        dic_key_awayTeam = awayTeam + str(i)

        HT_points = cum_pts[dic_key_homeTeam]
        AT_points = cum_pts[dic_key_awayTeam]
    
        playing_stat.set_value(index=i, col='HTP', value=HT_points)
        playing_stat.set_value(index=i, col='ATP', value=AT_points)

    return playing_stat, match_res, match_loc, match_line 

####################



# Apply to each dataset

# Changes the function to my new function.
#get_agg_points = get_agg_points_jnc


# print("Start: ")
# display(playing_statistics_1)
# playing_statistics_1 = get_agg_points(playing_statistics_1)
# print("After: ")
# display(playing_statistics_1)


# TODO: Já está testado e está a calcular correctamente!!!!
#       Colocar descomentado este na versão final!!!!
#       Ter em atenção que ele é chamado mais à frente.

print("Start: ")
display(playing_statistics_1)
playing_statistics_1, match_res_1, match_loc_1, match_line_1 = get_agg_points_jnc(playing_statistics_1, team_names_set_1)
print("After: ")
display(playing_statistics_1)


playing_statistics_2, match_res_2, match_loc_2, match_line_2 = get_agg_points_jnc(playing_statistics_2, team_names_set_2)
playing_statistics_3, match_res_3, match_loc_3, match_line_3 = get_agg_points_jnc(playing_statistics_3, team_names_set_3)
playing_statistics_4, match_res_4, match_loc_4, match_line_4 = get_agg_points_jnc(playing_statistics_4, team_names_set_4)
playing_statistics_5, match_res_5, match_loc_5, match_line_5 = get_agg_points_jnc(playing_statistics_5, team_names_set_5)
playing_statistics_6, match_res_6, match_loc_6, match_line_6 = get_agg_points_jnc(playing_statistics_6, team_names_set_6)
playing_statistics_7, match_res_7, match_loc_7, match_line_7 = get_agg_points_jnc(playing_statistics_7, team_names_set_7)
playing_statistics_8, match_res_8, match_loc_8, match_line_8 = get_agg_points_jnc(playing_statistics_8, team_names_set_8)
playing_statistics_9, match_res_9, match_loc_9, match_line_9 = get_agg_points_jnc(playing_statistics_9, team_names_set_9)
playing_statistics_10, match_res_10, match_loc_10, match_line_10 = get_agg_points_jnc(playing_statistics_10, team_names_set_10)
playing_statistics_11, match_res_11, match_loc_11, match_line_11 = get_agg_points_jnc(playing_statistics_11, team_names_set_11)
playing_statistics_12, match_res_12, match_loc_12, match_line_12 = get_agg_points_jnc(playing_statistics_12, team_names_set_12)
playing_statistics_13, match_res_13, match_loc_13, match_line_13 = get_agg_points_jnc(playing_statistics_13, team_names_set_13)
playing_statistics_14, match_res_14, match_loc_14, match_line_14 = get_agg_points_jnc(playing_statistics_14, team_names_set_14)

Start:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5
...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52

C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

After:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67

GET TEAM FORM:

In [11]:
#def get_form(playing_stat,num):
#    form = get_matchres(playing_stat)
#    form_final = form.copy()
#    for i in range(num,39):
#        form_final[i] = ''
#        j = 0
#        while j < num:
#            form_final[i] += form[i-j]
#            j += 1           
#    return form_final




#  HM1 AM1 HM2 AM2 HM3 AM3 HM4 AM4 HM5 AM5
#
#  M M M M M M M M M M
#  L W M M M M M M M M
#  W L L D M M M M M M

def add_form_df_jnc(playing_stat, match_res):
    
    # Creates the 2 pair of 5 columns with the values inicialized to M (No previous match).
    playing_stat['HM1'] = 'M'
    playing_stat['AM1'] = 'M'
    playing_stat['HM2'] = 'M'
    playing_stat['AM2'] = 'M'
    playing_stat['HM3'] = 'M'
    playing_stat['AM3'] = 'M'
    playing_stat['HM4'] = 'M'
    playing_stat['AM4'] = 'M'
    playing_stat['HM5'] = 'M'
    playing_stat['AM5'] = 'M'
    
    for i in range(0, len(playing_stat)):
        homeTeam = playing_stat.iloc[i].HomeTeam
        awayTeam = playing_stat.iloc[i].AwayTeam
           
        # Generate the goals_dic keys for the line for the home and away teams.
        dic_key_homeTeam = homeTeam + str(i)
        dic_key_awayTeam = awayTeam + str(i)

        matches_list_home = match_res[dic_key_homeTeam]
        matches_list_away = match_res[dic_key_awayTeam]
        
        # Home Team. 
        # NOTE: I think that the list is in reverse order, the zero position is
        #       the first game and the last position is the last game.
        #       But we wan't to transverse from the last to the first.
        length_home = len(matches_list_home)
        if (length_home >= 1):
            game_res = matches_list_home[-1] # 0
            playing_stat.set_value(index=i, col='HM1', value=game_res)
        if (length_home >= 2):
            game_res = matches_list_home[-2] # 0
            playing_stat.set_value(index=i, col='HM2', value=game_res)
        if (length_home >= 3):
            game_res = matches_list_home[-3]
            playing_stat.set_value(index=i, col='HM3', value=game_res)
        if (length_home >= 4):
            game_res = matches_list_home[-4]
            playing_stat.set_value(index=i, col='HM4', value=game_res)
        if (length_home >= 5):
            game_res = matches_list_home[-5]
            playing_stat.set_value(index=i, col='HM5', value=game_res)
        
        # Away Team.
        length_away = len(matches_list_away)
        if (length_away >= 1):
            game_res = matches_list_away[-1] # 0
            playing_stat.set_value(index=i, col='AM1', value=game_res)
        if (length_away >= 2):
            game_res = matches_list_away[-2] # 1
            playing_stat.set_value(index=i, col='AM2', value=game_res)
        if (length_away >= 3):
            game_res = matches_list_away[-3]
            playing_stat.set_value(index=i, col='AM3', value=game_res)
        if (length_away >= 4):
            game_res = matches_list_away[-4]
            playing_stat.set_value(index=i, col='AM4', value=game_res)
        if (length_away >= 5):
            game_res = matches_list_away[-5]
            playing_stat.set_value(index=i, col='AM5', value=game_res)

    return playing_stat    


##################################
##################################

#################################
#################################



# Make changes to df

# print("Start: ")
# display(playing_statistics_1)
# playing_statistics_1 = add_form_df(playing_statistics_1)
# print("After: ")
# display(playing_statistics_1)

print("Start: ")
display(playing_statistics_1)
playing_statistics_1 = add_form_df_jnc(playing_statistics_1, match_res_1)
print("After: ")
display(playing_statistics_1)


playing_statistics_2 = add_form_df_jnc(playing_statistics_2, match_res_2)
playing_statistics_3 = add_form_df_jnc(playing_statistics_3, match_res_3)
playing_statistics_4 = add_form_df_jnc(playing_statistics_4, match_res_4)
playing_statistics_5 = add_form_df_jnc(playing_statistics_5, match_res_5)
playing_statistics_6 = add_form_df_jnc(playing_statistics_6, match_res_6)
playing_statistics_7 = add_form_df_jnc(playing_statistics_7, match_res_7)
playing_statistics_8 = add_form_df_jnc(playing_statistics_8, match_res_8)
playing_statistics_9 = add_form_df_jnc(playing_statistics_9, match_res_9)
playing_statistics_10 = add_form_df_jnc(playing_statistics_10, match_res_10)
playing_statistics_11 = add_form_df_jnc(playing_statistics_11, match_res_11)
playing_statistics_12 = add_form_df_jnc(playing_statistics_12, match_res_12)
playing_statistics_13 = add_form_df_jnc(playing_statistics_13, match_res_13)
playing_statistics_14 = add_form_df_jnc(playing_statistics_14, match_res_14)

Start:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67

C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

After:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,D,M,M,M,M,M,M,M,M
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,D,M,M,M,M,M,M,M,M
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,W,M,M,M,M,M,M,M,M
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,W,M,M,M,M,M,M,M,M
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,D,M,M,M,M,M,M,M,M
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,D,M,M,M,M,M,M,M,M
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,W,M,M,M,M,M,M,M,M
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,D,M,M,M,M,M,M,M,M
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,W,M,M,M,M,M,M,M,M
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,D,M,M,M,M,M,M,M,M
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,W,M,M,M,M,M,M,M,M
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,W,M,M,M,M,M,M,M,M
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,W,D,D,M,M,M,M,M,M
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,L,W,M,M,M,M,M,M
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,D,L,W,M,M,M,M,M,M
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,D,L,W,M,M,M,M,M,M
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,W,D,D,M,M,M,M,M,M
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,L,D,D,M,M,M,M,M,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50,D,D,L,L,W,D,W,D,W,W
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66,W,L,L,D,L,W,L,W,L,D
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58,W,L,W,D,L,L,L,D,D,L
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28,D,L,W,L,D,L,D,W,D,L
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74,D,W,W,W,L,W,L,D,W,W
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73,L,W,D,W,L,W,D,W,D,L
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88,D,W,W,D,D,L,W,W,W,W
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52,L,D,W,L,D,W,L,W,L,D
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73,D,L,D,W,L,W,W,W,W,W
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50,L,W,D,D,W,L,D,L,D,W
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47,D,L,D,D,L,L,W,L,W,D
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83,L,D,W,W,W,W,W,L,D,L
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43,D,W,L,L,D,D,L,L,D,L
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60,L,W,W,D,W,W,W,D,D,D
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47,L,D,L,D,L,D,L,L,W,L
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62,D,W,L,D,D,W,W,L,W,L
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49,W,D,L,W,W,L,L,L,L,L
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59,W,D,L,D,D,W,L,L,D,D
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84,W,W,D,D,D,D,D,L,L,W
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62,D,W,W,D,D,L,L,D,L,L
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52,L,W,L,D,D,D,L,L,L,W
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75,L,D,L,L,W,W,W,W,W,W
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28,L,L,D,L,D,L,W,L,L,L
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59,W,W,W,L,D,W,W,D,L,L
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49,L,D,W,L,L,D,D,W,L,D
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56,L,W,D,W,L,L,W,D,W,L
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61,W,L,W,W,D,L,L,W,W,L
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70,W,L,D,D,W,W,L,D,L,W
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70,D,L,D,L,W,W,W,W,L,W
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67,W,L,W,D,D,L,W,D,D,W

In [12]:


# Add past games location H [home] vs A [Away].
def add_past_games_loc_df_jnc(playing_stat, match_loc):
    
    # 

    # TODO: Retirar, só para DEBUG, para mostrar a lista de jogos passados em sequencia.
    # playing_stat['HM_LIST'] = ""
    # playing_stat['AM_LIST'] = ""
    
    
    # Home team past matches location H [Home] ou A [Away].
    playing_stat['HM1_H'] = 0
    playing_stat['HM1_A'] = 0
    
    playing_stat['HM2_H'] = 0
    playing_stat['HM2_A'] = 0
    
    playing_stat['HM3_H'] = 0
    playing_stat['HM3_A'] = 0
    
    playing_stat['HM4_H'] = 0
    playing_stat['HM4_A'] = 0
    
    playing_stat['HM5_H'] = 0
    playing_stat['HM5_A'] = 0


    # Away team past matches location H [Home] ou A [Away].    
    playing_stat['AM1_H'] = 0
    playing_stat['AM1_A'] = 0
    
    playing_stat['AM2_H'] = 0
    playing_stat['AM2_A'] = 0
    
    playing_stat['AM3_H'] = 0
    playing_stat['AM3_A'] = 0
    
    playing_stat['AM4_H'] = 0
    playing_stat['AM4_A'] = 0
    
    playing_stat['AM5_H'] = 0
    playing_stat['AM5_A'] = 0
    
    
    for i in range(0, len(playing_stat)):
        homeTeam = playing_stat.iloc[i].HomeTeam
        awayTeam = playing_stat.iloc[i].AwayTeam
           
        # Generate the location_dic keys for the line for the home and away teams.
        dic_key_homeTeam = homeTeam + str(i)
        dic_key_awayTeam = awayTeam + str(i)

        matches_loc_list_home = match_loc[dic_key_homeTeam]
        matches_loc_list_away = match_loc[dic_key_awayTeam]
    
        # TODO: Retirar, só para DEBUG.
        # playing_stat.set_value(index=i, col='HM_LIST', value=''.join(matches_loc_list_home))
        # playing_stat.set_value(index=i, col='AM_LIST', value=''.join(matches_loc_list_away))
    
    
        # Home Team. 
        # NOTE: I think that the list is in reverse order, the zero position is
        #       the first game and the last position is the last game.
        #       But we wan't to transverse from the last to the first.
        length_home = len(matches_loc_list_home)
        if (length_home >= 1):
            game_res = matches_loc_list_home[-1] # 0
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='HM1_H', value=1)
            else:
                playing_stat.set_value(index=i, col='HM1_A', value=1)
        if (length_home >= 2):
            game_res = matches_loc_list_home[-2]
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='HM2_H', value=1)
            else:
                playing_stat.set_value(index=i, col='HM2_A', value=1)
        if (length_home >= 3):
            game_res = matches_loc_list_home[-3]
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='HM3_H', value=1)
            else:
                playing_stat.set_value(index=i, col='HM3_A', value=1)
        if (length_home >= 4):
            game_res = matches_loc_list_home[-4]
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='HM4_H', value=1)
            else:
                playing_stat.set_value(index=i, col='HM4_A', value=1)
        if (length_home >= 5):
            game_res = matches_loc_list_home[-5]
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='HM5_H', value=1)
            else:
                playing_stat.set_value(index=i, col='HM5_A', value=1)
                
                
        # Away Team.                
        length_away = len(matches_loc_list_away)
        if (length_away >= 1):
            game_res = matches_loc_list_away[-1] # 0
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='AM1_H', value=1)
            else:
                playing_stat.set_value(index=i, col='AM1_A', value=1)
        if (length_away >= 2):
            game_res = matches_loc_list_away[-2]
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='AM2_H', value=1)
            else:
                playing_stat.set_value(index=i, col='AM2_A', value=1)
        if (length_away >= 3):
            game_res = matches_loc_list_away[-3]
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='AM3_H', value=1)
            else:
                playing_stat.set_value(index=i, col='AM3_A', value=1)
        if (length_away >= 4):
            game_res = matches_loc_list_away[-4]
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='AM4_H', value=1)
            else:
                playing_stat.set_value(index=i, col='AM4_A', value=1)
        if (length_away >= 5):
            game_res = matches_loc_list_away[-5]
            if game_res == 'H': 
                playing_stat.set_value(index=i, col='AM5_H', value=1)
            else:
                playing_stat.set_value(index=i, col='AM5_A', value=1)
    
    
    return playing_stat    


    
print("Start: ")
display(playing_statistics_1)
playing_statistics_1 = add_past_games_loc_df_jnc(playing_statistics_1, match_loc_1)
print("After: ")
display(playing_statistics_1)
    
 
playing_statistics_2 = add_past_games_loc_df_jnc(playing_statistics_2, match_loc_2)
playing_statistics_3 = add_past_games_loc_df_jnc(playing_statistics_3, match_loc_3)
playing_statistics_4 = add_past_games_loc_df_jnc(playing_statistics_4, match_loc_4)
playing_statistics_5 = add_past_games_loc_df_jnc(playing_statistics_5, match_loc_5)
playing_statistics_6 = add_past_games_loc_df_jnc(playing_statistics_6, match_loc_6)
playing_statistics_7 = add_past_games_loc_df_jnc(playing_statistics_7, match_loc_7)
playing_statistics_8 = add_past_games_loc_df_jnc(playing_statistics_8, match_loc_8)
playing_statistics_9 = add_past_games_loc_df_jnc(playing_statistics_9, match_loc_9)
playing_statistics_10 = add_past_games_loc_df_jnc(playing_statistics_10, match_loc_10)
playing_statistics_11 = add_past_games_loc_df_jnc(playing_statistics_11, match_loc_11)
playing_statistics_12 = add_past_games_loc_df_jnc(playing_statistics_12, match_loc_12)
playing_statistics_13 = add_past_games_loc_df_jnc(playing_statistics_13, match_loc_13)
playing_statistics_14 = add_past_games_loc_df_jnc(playing_statistics_14, match_loc_14)

Start:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,D,M,M,M,M,M,M,M,M
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,D,M,M,M,M,M,M,M,M
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,W,M,M,M,M,M,M,M,M
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,W,M,M,M,M,M,M,M,M
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,D,M,M,M,M,M,M,M,M
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,D,M,M,M,M,M,M,M,M
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,W,M,M,M,M,M,M,M,M
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,D,M,M,M,M,M,M,M,M
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,W,M,M,M,M,M,M,M,M
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,D,M,M,M,M,M,M,M,M
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,W,M,M,M,M,M,M,M,M
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,W,M,M,M,M,M,M,M,M
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,W,D,D,M,M,M,M,M,M
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,L,W,M,M,M,M,M,M
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,D,L,W,M,M,M,M,M,M
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,D,L,W,M,M,M,M,M,M
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,W,D,D,M,M,M,M,M,M
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,L,D,D,M,M,M,M,M,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50,D,D,L,L,W,D,W,D,W,W
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66,W,L,L,D,L,W,L,W,L,D
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58,W,L,W,D,L,L,L,D,D,L
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28,D,L,W,L,D,L,D,W,D,L
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74,D,W,W,W,L,W,L,D,W,W
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73,L,W,D,W,L,W,D,W,D,L
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88,D,W,W,D,D,L,W,W,W,W
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52,L,D,W,L,D,W,L,W,L,D
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73,D,L,D,W,L,W,W,W,W,W
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50,L,W,D,D,W,L,D,L,D,W
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47,D,L,D,D,L,L,W,L,W,D
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83,L,D,W,W,W,W,W,L,D,L
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43,D,W,L,L,D,D,L,L,D,L
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60,L,W,W,D,W,W,W,D,D,D
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47,L,D,L,D,L,D,L,L,W,L
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62,D,W,L,D,D,W,W,L,W,L
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49,W,D,L,W,W,L,L,L,L,L
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59,W,D,L,D,D,W,L,L,D,D
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84,W,W,D,D,D,D,D,L,L,W
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62,D,W,W,D,D,L,L,D,L,L
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52,L,W,L,D,D,D,L,L,L,W
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75,L,D,L,L,W,W,W,W,W,W
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28,L,L,D,L,D,L,W,L,L,L
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59,W,W,W,L,D,W,W,D,L,L
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49,L,D,W,L,L,D,D,W,L,D
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56,L,W,D,W,L,L,W,D,W,L
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61,W,L,W,W,D,L,L,W,W,L
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70,W,L,D,D,W,W,L,D,L,W
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70,D,L,D,L,W,W,W,W,L,W
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67,W,L,W,D,D,L,W,D,D,W

C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\JNC\Anaconda3\lib\site-packages\ipykernel_launcher.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

After:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,D,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,D,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,W,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,W,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,D,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,D,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,W,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,D,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,W,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,D,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,W,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,W,M,M,M,M,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,W,D,D,M,M,M,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,L,W,M,M,M,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,D,L,W,M,M,M,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,D,L,W,M,M,M,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,W,D,D,M,M,M,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,L,D,D,M,M,M,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50,D,D,L,L,W,D,W,D,W,W,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66,W,L,L,D,L,W,L,W,L,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58,W,L,W,D,L,L,L,D,D,L,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28,D,L,W,L,D,L,D,W,D,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,0,1,1,0
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74,D,W,W,W,L,W,L,D,W,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73,L,W,D,W,L,W,D,W,D,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88,D,W,W,D,D,L,W,W,W,W,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,0,1
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52,L,D,W,L,D,W,L,W,L,D,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73,D,L,D,W,L,W,W,W,W,W,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50,L,W,D,D,W,L,D,L,D,W,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,0,1
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47,D,L,D,D,L,L,W,L,W,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83,L,D,W,W,W,W,W,L,D,L,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43,D,W,L,L,D,D,L,L,D,L,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,1,0,0,1
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60,L,W,W,D,W,W,W,D,D,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,0,1,0,1
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47,L,D,L,D,L,D,L,L,W,L,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62,D,W,L,D,D,W,W,L,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49,W,D,L,W,W,L,L,L,L,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59,W,D,L,D,D,W,L,L,D,D,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84,W,W,D,D,D,D,D,L,L,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62,D,W,W,D,D,L,L,D,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52,L,W,L,D,D,D,L,L,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75,L,D,L,L,W,W,W,W,W,W,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28,L,L,D,L,D,L,W,L,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59,W,W,W,L,D,W,W,D,L,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49,L,D,W,L,L,D,D,W,L,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56,L,W,D,W,L,L,W,D,W,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61,W,L,W,W,D,L,L,W,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70,W,L,D,D,W,W,L,D,L,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,1,0,1,0
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70,D,L,D,L,W,W,W,W,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67,W,L,W,D,D,L,W,D,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0

In [13]:
# Rearranging columns
cols = ['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTGS', 'ATGS', 'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3',
        'HM4', 'HM5', 'AM1', 'AM2', 'AM3', 'AM4', 'AM5',
        'HM1_H', 'HM1_A', 
        'HM2_H', 'HM2_A',
        'HM3_H', 'HM3_A',
        'HM4_H', 'HM4_A',
        'HM5_H', 'HM5_A',
        'AM1_H', 'AM1_A',
        'AM2_H', 'AM2_A',
        'AM3_H', 'AM3_A',
        'AM4_H', 'AM4_A',
        'AM5_H', 'AM5_A']



playing_statistics_1 = playing_statistics_1[cols]
playing_statistics_2 = playing_statistics_2[cols]
playing_statistics_3 = playing_statistics_3[cols]
playing_statistics_4 = playing_statistics_4[cols]
playing_statistics_5 = playing_statistics_5[cols]
playing_statistics_6 = playing_statistics_6[cols]
playing_statistics_7 = playing_statistics_7[cols]
playing_statistics_8 = playing_statistics_8[cols]
playing_statistics_9 = playing_statistics_9[cols]
playing_statistics_10 = playing_statistics_10[cols]
playing_statistics_11 = playing_statistics_11[cols]
playing_statistics_12 = playing_statistics_12[cols]
playing_statistics_13 = playing_statistics_13[cols]
playing_statistics_14 = playing_statistics_14[cols]

Get Last Year's Position as also an independent variable:

In [14]:
# TODO MUITO IMPORTANTE:
#     O ficheiro do EPLStandings.csv tem de ser actualizado manualmente tenho de fazer uma
#     versão para este ano com o resultados das posições dos jogos da época anterior de 2016-2017,
#     a época actual é de 2017-2018.

#Standings = pd.read_csv(loc + "EPLStandings.csv")

# JNC com os jogos actualizados de 2016-2017 para prever a epoca de 2017. 
#Standings = pd.read_csv(loc + "EPLStandings_new.csv")

#Standings.set_index(['Team'], inplace=True)

#print("EPLStanding.csv file with last years position: ")
#display(Standings)


# MUITO IMPORTANTE: Até para a champions, não esquecer de fazer algo parecido.
#Standings = Standings.fillna(18)

#def get_last(playing_stat, Standings, year):
#    HomeTeamLP = []
#    AwayTeamLP = []
#    for i in range(380):
#        ht = playing_stat.iloc[i].HomeTeam
#        at = playing_stat.iloc[i].AwayTeam
#        HomeTeamLP.append(Standings.loc[ht][year])
#        AwayTeamLP.append(Standings.loc[at][year])
#    playing_stat['HomeTeamLP'] = HomeTeamLP
#    playing_stat['AwayTeamLP'] = AwayTeamLP
#    return playing_stat


####################
# JNC Version

def get_last_jnc(playing_stat, Standings, year):

    # Creates the Home Team Last Years Position, 
    # and the Away Team Last Year Position,
    # inicialized to 0.0 (zero) [dummy value, that will be overwrited].
    playing_stat['HomeTeamLP'] = 0.0
    playing_stat['AwayTeamLP'] = 0.0
        
    for i in range(0, len(playing_stat)):
        homeTeam = playing_stat.iloc[i].HomeTeam
        awayTeam = playing_stat.iloc[i].AwayTeam
        
        last_year_home_team_position = Standings.loc[homeTeam][year]
        playing_stat.set_value(index=i, col='HomeTeamLP', value=last_year_home_team_position)
        
        last_year_away_team_position = Standings.loc[awayTeam][year]
        playing_stat.set_value(index=i, col='AwayTeamLP', value=last_year_away_team_position)

    return playing_stat


def get_last_jnc_champions(playing_stat, Standings, year):

    # Creates the Home Team Last Years Position, 
    # and the Away Team Last Year Position,
    # inicialized to 0.0 (zero) [dummy value, that will be overwrited].
    playing_stat['HomeTeamLP'] = 0.0
    playing_stat['AwayTeamLP'] = 0.0
        
    for i in range(0, len(playing_stat)):
        homeTeam = playing_stat.iloc[i].HomeTeam
        awayTeam = playing_stat.iloc[i].AwayTeam
        
        # last_year_home_team_position = Standings.loc[homeTeam][year]
        last_year_home_team_position = get_last_year_team_name_position(standings, homeTeam, year, empty_value = 22)
        playing_stat.set_value(index=i, col='HomeTeamLP', value=last_year_home_team_position)
        
        # last_year_away_team_position = Standings.loc[awayTeam][year]
        last_year_away_team_position = get_last_year_team_name_position(standings, awayTeam, year, empty_value = 22)
        playing_stat.set_value(index=i, col='AwayTeamLP', value=last_year_away_team_position)

    return playing_stat 

#######################


#print("Start: ")
#display(playing_statistics_1)
#playing_statistics_1 = get_last(playing_statistics_1, Standings, 0)
#print("After: ")
#display(playing_statistics_1)


print("Start: ")
display(playing_statistics_1)
# Este ano é o 1º ano por isso não existe Last year, talvez o retire no processamento, por não ter last.
playing_statistics_1 = get_last_jnc_champions(playing_statistics_1, standings, 2003)
print("After: ")
display(playing_statistics_1)

# TODO: Descomentar
playing_statistics_2 = get_last_jnc_champions(playing_statistics_2, standings, 2004)
playing_statistics_3 = get_last_jnc_champions(playing_statistics_3, standings, 2005)
playing_statistics_4 = get_last_jnc_champions(playing_statistics_4, standings, 2006)
playing_statistics_5 = get_last_jnc_champions(playing_statistics_5, standings, 2007)
playing_statistics_6 = get_last_jnc_champions(playing_statistics_6, standings, 2008)
playing_statistics_7 = get_last_jnc_champions(playing_statistics_7, standings, 2009)
playing_statistics_8 = get_last_jnc_champions(playing_statistics_8, standings, 2010)
playing_statistics_9 = get_last_jnc_champions(playing_statistics_9, standings, 2011)
playing_statistics_10 = get_last_jnc_champions(playing_statistics_10, standings, 2012)
playing_statistics_11 = get_last_jnc_champions(playing_statistics_11, standings, 2013)
playing_statistics_12 = get_last_jnc_champions(playing_statistics_12, standings, 2014)
playing_statistics_13 = get_last_jnc_champions(playing_statistics_13, standings, 2015)

print("Start: ")
display(playing_statistics_14)
playing_statistics_14 = get_last_jnc_champions(playing_statistics_14, standings, 2016)
print("After: ")
display(playing_statistics_14)

Start:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,D,M,M,M,L,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50,D,L,W,W,W,D,L,D,D,W,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66,W,L,L,L,L,L,D,W,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58,W,W,L,L,D,L,D,L,D,L,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28,D,W,D,D,D,L,L,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,0,1,1,0
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74,D,W,L,L,W,W,W,W,D,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73,L,D,L,D,D,W,W,W,W,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88,D,W,D,W,W,W,D,L,W,W,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,0,1
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52,L,W,D,L,L,D,L,W,W,D,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73,D,D,L,W,W,L,W,W,W,W,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50,L,D,W,D,D,W,D,L,L,W,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,0,1
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47,D,D,L,W,W,L,D,L,L,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83,L,W,W,W,D,D,W,W,L,L,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43,D,L,D,L,D,W,L,D,L,L,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,1,0,0,1
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60,L,W,W,W,D,W,D,W,D,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,0,1,0,1
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47,L,L,L,L,W,D,D,D,L,L,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62,D,L,D,W,W,W,D,W,L,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49,W,L,W,L,L,D,W,L,L,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59,W,L,D,L,D,D,D,W,L,D,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84,W,D,D,D,L,W,D,D,L,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62,D,W,D,L,L,W,D,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52,L,L,D,L,L,W,D,D,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75,L,L,W,W,W,D,L,W,W,W,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28,L,D,D,W,L,L,L,L,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59,W,W,D,W,L,W,L,W,D,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49,L,W,L,D,L,D,L,D,W,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56,L,D,L,W,W,W,W,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61,W,W,D,L,W,L,W,L,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70,W,D,W,L,L,L,D,W,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,1,0,1,0
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70,D,D,W,W,L,L,L,W,W,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67,W,W,D,W,D,L,D,L,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0

After:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A,HomeTeamLP,AwayTeamLP
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,D,M,M,M,L,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50,D,L,W,W,W,D,L,D,D,W,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,22.0,22.0
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66,W,L,L,L,L,L,D,W,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58,W,W,L,L,D,L,D,L,D,L,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,22.0,22.0
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28,D,W,D,D,D,L,L,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,0,1,1,0,22.0,22.0
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74,D,W,L,L,W,W,W,W,D,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73,L,D,L,D,D,W,W,W,W,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88,D,W,D,W,W,W,D,L,W,W,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52,L,W,D,L,L,D,L,W,W,D,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73,D,D,L,W,W,L,W,W,W,W,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,22.0,22.0
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50,L,D,W,D,D,W,D,L,L,W,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,0,1,22.0,22.0
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47,D,D,L,W,W,L,D,L,L,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83,L,W,W,W,D,D,W,W,L,L,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43,D,L,D,L,D,W,L,D,L,L,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60,L,W,W,W,D,W,D,W,D,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47,L,L,L,L,W,D,D,D,L,L,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62,D,L,D,W,W,W,D,W,L,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49,W,L,W,L,L,D,W,L,L,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59,W,L,D,L,D,D,D,W,L,D,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,22.0,22.0
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84,W,D,D,D,L,W,D,D,L,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,22.0,22.0
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62,D,W,D,L,L,W,D,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,22.0,22.0
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52,L,L,D,L,L,W,D,D,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75,L,L,W,W,W,D,L,W,W,W,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28,L,D,D,W,L,L,L,L,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59,W,W,D,W,L,W,L,W,D,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,22.0,22.0
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49,L,W,L,D,L,D,L,D,W,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56,L,D,L,W,W,W,W,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,22.0,22.0
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61,W,W,D,L,W,L,W,L,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,22.0,22.0
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70,W,D,W,L,L,L,D,W,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,1,0,1,0,22.0,22.0
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70,D,D,W,W,L,L,L,W,W,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67,W,W,D,W,D,L,D,L,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,22.0,22.0

Start:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A
0,2017-08-04,Nott'm Forest,Millwall,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2017-08-04,Sunderland,Derby,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2017-08-05,Aston Villa,Hull,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2017-08-05,Bristol City,Barnsley,3,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2017-08-05,Burton,Cardiff,0,1,A,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,2017-08-05,Fulham,Norwich,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,2017-08-05,Ipswich,Birmingham,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,2017-08-05,Preston,Sheffield Weds,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,2017-08-05,QPR,Reading,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,2017-08-05,Sheffield United,Brentford,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,2017-08-05,Wolves,Middlesbrough,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,2017-08-06,Bolton,Leeds,2,3,A,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,2017-08-12,Barnsley,Ipswich,1,2,A,1,1,3,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
13,2017-08-12,Birmingham,Bristol City,2,1,H,0,3,1,1,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
14,2017-08-12,Brentford,Nott'm Forest,3,4,A,0,1,1,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
15,2017-08-12,Cardiff,Aston Villa,3,0,H,1,1,0,1,3,1,W,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
16,2017-08-12,Derby,Wolves,0,2,A,1,1,1,0,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
17,2017-08-12,Hull,Burton,4,1,H,1,0,1,1,1,0,D,M,M,M,M,L,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
18,2017-08-12,Leeds,Preston,0,0,D,3,1,2,0,3,3,W,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
19,2017-08-12,Middlesbrough,Sheffield United,1,0,H,0,1,1,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
20,2017-08-12,Millwall,Bolton,1,1,D,0,2,1,3,0,0,L,M,M,M,M,L,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
21,2017-08-12,Reading,Fulham,1,1,D,0,1,2,1,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22,2017-08-12,Sheffield Weds,QPR,1,1,D,0,2,1,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
23,2017-08-13,Norwich,Sunderland,1,3,A,1,1,1,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
24,2017-08-15,Barnsley,Nott'm Forest,2,1,H,2,5,5,3,0,6,L,L,M,M,M,W,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
25,2017-08-15,Birmingham,Bolton,0,0,D,2,3,2,4,3,1,W,L,M,M,M,D,L,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
26,2017-08-15,Brentford,Bristol City,2,2,D,3,4,5,3,0,3,L,L,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
27,2017-08-15,Cardiff,Sheffield United,2,0,H,4,1,0,1,6,3,W,W,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
28,2017-08-15,Derby,Preston,1,0,H,1,1,3,0,1,4,L,D,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
29,2017-08-15,Hull,Wolves,2,3,A,5,3,2,0,4,6,W,D,M,M,M,W,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2017-09-23,Preston,Millwall,0,0,D,9,11,3,9,15,9,W,W,D,D,W,W,D,L,W,D,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,0,1
101,2017-09-23,QPR,Burton,0,0,D,12,6,12,15,11,8,L,D,W,L,W,W,D,L,D,W,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0
102,2017-09-23,Reading,Hull,1,1,D,6,14,7,15,8,8,D,L,W,L,W,D,L,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1
103,2017-09-23,Sunderland,Cardiff,1,2,A,7,12,12,7,6,17,D,L,L,L,L,D,L,D,W,W,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,0,1
104,2017-09-23,Wolves,Barnsley,2,1,H,13,8,8,11,17,7,W,D,W,D,L,L,D,W,L,W,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0
105,2017-09-24,Sheffield Weds,Sheffield United,2,4,A,10,8,7,6,13,15,D,W,W,D,W,L,W,W,W,W,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,1,0
106,2017-09-26,Barnsley,QPR,1,1,D,9,12,13,12,7,12,L,L,D,W,L,D,L,D,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1
107,2017-09-26,Brentford,Derby,1,1,D,10,12,12,12,7,11,W,D,L,D,D,D,L,W,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1
108,2017-09-26,Bristol City,Bolton,2,0,H,15,4,10,19,14,2,D,W,D,W,D,L,L,L,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
109,2017-09-26,Burton,Aston Villa,0,4,A,6,12,15,10,9,13,D,W,D,L,D,W,W,D,D,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
110,2017-09-26,Cardiff,Leeds,3,1,H,14,17,8,5,20,20,W,D,L,D,W,W,L,W,W,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
111,2017-09-26,Hull,Preston,1,2,A,15,9,16,3,9,16,D,D,L,L,W,D,W,W,D,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
112,2017-09-26,Ipswich,Sunderland,5,2,H,14,8,11,14,15,6,L,W,L,L,W,L,D,L,L,L,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1
113,2017-09-26,Middlesbrough,Norwich,0,1,A,11,8,6,12,15,12,D,W,D,W,D,D,W,D,W,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
114,2017-09-26,Millwall,Reading,2,1,H,11,7,9,8,10,9,D,W,D,L,W,D,D,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1
115,2017-09-26,Nott'm Forest,Fulham,1,3,A,12,9,15,8,12,11,L,L,W,L,L,D,L,W,D,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
116,2017-09-27,Birmingham,Sheffield Weds,1,0,H,5,12,13,11,5,13,D,L,L,L,L,L,D,W,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
117,2017-09-27,Sheffield United,Wolves,2,0,H,12,15,8,9,18,20,W,L,W,W,W,W,W,D,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1
118,2017-09-29,QPR,Fulham,0,0,,13,12,13,9,13,14,D,D,L,D,W,W,D,L,W,D,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0
119,2017-09-30,Preston,Sunderland,0,0,,11,10,4,19,19,6,W,D,W,W,D,L,L,D,L,L,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0
120,2017-09-30,Aston Villa,Bolton,0,0,,16,4,10,21,16,2,W,W,W,D,D,L,L,L,L,L,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0
121,2017-09-30,Middlesbrough,Brentford,0,0,,11,11,7,13,15,8,L,D,W,D,W,D,W,D,L,D,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1
122,2017-09-30,Burton,Wolves,0,0,,6,15,19,11,9,20,L,D,W,D,L,L,W,W,D,W,1,0,0,1,1,0,0,1,0,1,0,1,1,0,0,1,1,0,1,0
123,2017-09-30,Ipswich,Bristol City,0,0,,19,17,13,10,18,17,W,L,W,L,L,W,D,W,D,W,1,0,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1
124,2017-09-30,Millwall,Barnsley,0,0,,13,10,10,14,13,8,W,D,W,D,L,D,L,L,D,W,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0
125,2017-09-30,Nott'm Forest,Sheffield United,0,0,,13,14,18,8,12,21,L,L,L,W,L,W,W,L,W,W,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1
126,2017-09-30,Hull,Birmingham,0,0,,16,6,18,13,9,8,L,D,D,L,L,W,D,L,L,L,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1
127,2017-09-30,Cardiff,Derby,0,0,,17,13,9,13,23,12,W,W,D,L,D,D,D,L,W,L,1,0,0,1,1,0,0,1,0,1,0,1,1,0,0,1,1,0,0,1
128,2017-09-30,Reading,Norwich,0,0,,8,9,10,12,9,15,L,D,D,L,W,W,D,W,D,W,0,1,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0
129,2017-10-01,Sheffield Weds,Leeds,0,0,,12,18,12,8,13,20,L,L,D,W,W,L,W,L,W,W,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0

After:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A,HomeTeamLP,AwayTeamLP
0,2017-08-04,Nott'm Forest,Millwall,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21.0,22.0
1,2017-08-04,Sunderland,Derby,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,9.0
2,2017-08-05,Aston Villa,Hull,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13.0,22.0
3,2017-08-05,Bristol City,Barnsley,3,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17.0,14.0
4,2017-08-05,Burton,Cardiff,0,1,A,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20.0,12.0
5,2017-08-05,Fulham,Norwich,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.0,8.0
6,2017-08-05,Ipswich,Birmingham,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16.0,19.0
7,2017-08-05,Preston,Sheffield Weds,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.0,4.0
8,2017-08-05,QPR,Reading,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18.0,3.0
9,2017-08-05,Sheffield United,Brentford,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,10.0
10,2017-08-05,Wolves,Middlesbrough,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15.0,22.0
11,2017-08-06,Bolton,Leeds,2,3,A,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,7.0
12,2017-08-12,Barnsley,Ipswich,1,2,A,1,1,3,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,14.0,16.0
13,2017-08-12,Birmingham,Bristol City,2,1,H,0,3,1,1,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,19.0,17.0
14,2017-08-12,Brentford,Nott'm Forest,3,4,A,0,1,1,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,10.0,21.0
15,2017-08-12,Cardiff,Aston Villa,3,0,H,1,1,0,1,3,1,W,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,12.0,13.0
16,2017-08-12,Derby,Wolves,0,2,A,1,1,1,0,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,9.0,15.0
17,2017-08-12,Hull,Burton,4,1,H,1,0,1,1,1,0,D,M,M,M,M,L,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,20.0
18,2017-08-12,Leeds,Preston,0,0,D,3,1,2,0,3,3,W,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,7.0,11.0
19,2017-08-12,Middlesbrough,Sheffield United,1,0,H,0,1,1,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
20,2017-08-12,Millwall,Bolton,1,1,D,0,2,1,3,0,0,L,M,M,M,M,L,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
21,2017-08-12,Reading,Fulham,1,1,D,0,1,2,1,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,3.0,6.0
22,2017-08-12,Sheffield Weds,QPR,1,1,D,0,2,1,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,4.0,18.0
23,2017-08-13,Norwich,Sunderland,1,3,A,1,1,1,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,8.0,22.0
24,2017-08-15,Barnsley,Nott'm Forest,2,1,H,2,5,5,3,0,6,L,L,M,M,M,W,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,14.0,21.0
25,2017-08-15,Birmingham,Bolton,0,0,D,2,3,2,4,3,1,W,L,M,M,M,D,L,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,19.0,22.0
26,2017-08-15,Brentford,Bristol City,2,2,D,3,4,5,3,0,3,L,L,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,10.0,17.0
27,2017-08-15,Cardiff,Sheffield United,2,0,H,4,1,0,1,6,3,W,W,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,12.0,22.0
28,2017-08-15,Derby,Preston,1,0,H,1,1,3,0,1,4,L,D,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,9.0,11.0
29,2017-08-15,Hull,Wolves,2,3,A,5,3,2,0,4,6,W,D,M,M,M,W,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2017-09-23,Preston,Millwall,0,0,D,9,11,3,9,15,9,W,W,D,D,W,W,D,L,W,D,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,0,1,11.0,22.0
101,2017-09-23,QPR,Burton,0,0,D,12,6,12,15,11,8,L,D,W,L,W,W,D,L,D,W,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,18.0,20.0
102,2017-09-23,Reading,Hull,1,1,D,6,14,7,15,8,8,D,L,W,L,W,D,L,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,3.0,22.0
103,2017-09-23,Sunderland,Cardiff,1,2,A,7,12,12,7,6,17,D,L,L,L,L,D,L,D,W,W,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,0,1,22.0,12.0
104,2017-09-23,Wolves,Barnsley,2,1,H,13,8,8,11,17,7,W,D,W,D,L,L,D,W,L,W,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,15.0,14.0
105,2017-09-24,Sheffield Weds,Sheffield United,2,4,A,10,8,7,6,13,15,D,W,W,D,W,L,W,W,W,W,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,1,0,4.0,22.0
106,2017-09-26,Barnsley,QPR,1,1,D,9,12,13,12,7,12,L,L,D,W,L,D,L,D,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,14.0,18.0
107,2017-09-26,Brentford,Derby,1,1,D,10,12,12,12,7,11,W,D,L,D,D,D,L,W,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,10.0,9.0
108,2017-09-26,Bristol City,Bolton,2,0,H,15,4,10,19,14,2,D,W,D,W,D,L,L,L,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,17.0,22.0
109,2017-09-26,Burton,Aston Villa,0,4,A,6,12,15,10,9,13,D,W,D,L,D,W,W,D,D,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,20.0,13.0
110,2017-09-26,Cardiff,Leeds,3,1,H,14,17,8,5,20,20,W,D,L,D,W,W,L,W,W,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,12.0,7.0
111,2017-09-26,Hull,Preston,1,2,A,15,9,16,3,9,16,D,D,L,L,W,D,W,W,D,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,11.0
112,2017-09-26,Ipswich,Sunderland,5,2,H,14,8,11,14,15,6,L,W,L,L,W,L,D,L,L,L,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1,16.0,22.0
113,2017-09-26,Middlesbrough,Norwich,0,1,A,11,8,6,12,15,12,D,W,D,W,D,D,W,D,W,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,8.0
114,2017-09-26,Millwall,Reading,2,1,H,11,7,9,8,10,9,D,W,D,L,W,D,D,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,3.0
115,2017-09-26,Nott'm Forest,Fulham,1,3,A,12,9,15,8,12,11,L,L,W,L,L,D,L,W,D,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,21.0,6.0
116,2017-09-27,Birmingham,Sheffield Weds,1,0,H,5,12,13,11,5,13,D,L,L,L,L,L,D,W,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,19.0,4.0
117,2017-09-27,Sheffield United,Wolves,2,0,H,12,15,8,9,18,20,W,L,W,W,W,W,W,D,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,15.0
118,2017-09-29,QPR,Fulham,0,0,,13,12,13,9,13,14,D,D,L,D,W,W,D,L,W,D,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,18.0,6.0
119,2017-09-30,Preston,Sunderland,0,0,,11,10,4,19,19,6,W,D,W,W,D,L,L,D,L,L,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,11.0,22.0
120,2017-09-30,Aston Villa,Bolton,0,0,,16,4,10,21,16,2,W,W,W,D,D,L,L,L,L,L,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,13.0,22.0
121,2017-09-30,Middlesbrough,Brentford,0,0,,11,11,7,13,15,8,L,D,W,D,W,D,W,D,L,D,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1,22.0,10.0
122,2017-09-30,Burton,Wolves,0,0,,6,15,19,11,9,20,L,D,W,D,L,L,W,W,D,W,1,0,0,1,1,0,0,1,0,1,0,1,1,0,0,1,1,0,1,0,20.0,15.0
123,2017-09-30,Ipswich,Bristol City,0,0,,19,17,13,10,18,17,W,L,W,L,L,W,D,W,D,W,1,0,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,16.0,17.0
124,2017-09-30,Millwall,Barnsley,0,0,,13,10,10,14,13,8,W,D,W,D,L,D,L,L,D,W,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0,22.0,14.0
125,2017-09-30,Nott'm Forest,Sheffield United,0,0,,13,14,18,8,12,21,L,L,L,W,L,W,W,L,W,W,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1,21.0,22.0
126,2017-09-30,Hull,Birmingham,0,0,,16,6,18,13,9,8,L,D,D,L,L,W,D,L,L,L,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1,22.0,19.0
127,2017-09-30,Cardiff,Derby,0,0,,17,13,9,13,23,12,W,W,D,L,D,D,D,L,W,L,1,0,0,1,1,0,0,1,0,1,0,1,1,0,0,1,1,0,0,1,12.0,9.0
128,2017-09-30,Reading,Norwich,0,0,,8,9,10,12,9,15,L,D,D,L,W,W,D,W,D,W,0,1,1,0,0,1,1,0,0,1,0,1,1,0,0,1,1,0,1,0,3.0,8.0
129,2017-10-01,Sheffield Weds,Leeds,0,0,,12,18,12,8,13,20,L,L,D,W,W,L,W,L,W,W,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,1,0,4.0,7.0

Get MatchWeek:

In [15]:
#def get_mw(playing_stat):
#    j = 1
#    MatchWeek = []
#    for i in range(380):
#        MatchWeek.append(j)
#        if ((i + 1)% 10) == 0:
#            j = j + 1
#    playing_stat['MW'] = MatchWeek
#    return playing_stat

###################
# JNC Version

### NOTE: As variaveis e constantes seguintes estão no inicio do programa/Jupyter Notebook.

# number_of_teams_in_EPL           = 20
# number_of_teams_in_primeira_liga = 18

# number_of_teams = number_of_teams_in_EPL

def get_mw_jnc(playing_stat):
    
    playing_stat['MW'] = 0
    
    for i in range(0, len(playing_stat)):
        num_week = (i / (number_of_teams / 2.0)) + 1 
        playing_stat.set_value(index=i, col='MW', value=num_week)
        
    return playing_stat

###################


# print("Start: ")
# display(playing_statistics_1)
# playing_statistics_1 = get_mw(playing_statistics_1)
# print("After: ")
# display(playing_statistics_1)

print("Start jnc: ")
display(playing_statistics_1)
playing_statistics_1 = get_mw_jnc(playing_statistics_1)
print("After jnc: ")
display(playing_statistics_1)


playing_statistics_2 = get_mw_jnc(playing_statistics_2)
playing_statistics_3 = get_mw_jnc(playing_statistics_3)
playing_statistics_4 = get_mw_jnc(playing_statistics_4)
playing_statistics_5 = get_mw_jnc(playing_statistics_5)
playing_statistics_6 = get_mw_jnc(playing_statistics_6)
playing_statistics_7 = get_mw_jnc(playing_statistics_7)
playing_statistics_8 = get_mw_jnc(playing_statistics_8)
playing_statistics_9 = get_mw_jnc(playing_statistics_9)
playing_statistics_10 = get_mw_jnc(playing_statistics_10)
playing_statistics_11 = get_mw_jnc(playing_statistics_11)
playing_statistics_12 = get_mw_jnc(playing_statistics_12)
playing_statistics_13 = get_mw_jnc(playing_statistics_13)
playing_statistics_14 = get_mw_jnc(playing_statistics_14)

Start jnc:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A,HomeTeamLP,AwayTeamLP
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,D,M,M,M,L,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50,D,L,W,W,W,D,L,D,D,W,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,22.0,22.0
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66,W,L,L,L,L,L,D,W,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58,W,W,L,L,D,L,D,L,D,L,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,22.0,22.0
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28,D,W,D,D,D,L,L,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,0,1,1,0,22.0,22.0
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74,D,W,L,L,W,W,W,W,D,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73,L,D,L,D,D,W,W,W,W,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88,D,W,D,W,W,W,D,L,W,W,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52,L,W,D,L,L,D,L,W,W,D,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73,D,D,L,W,W,L,W,W,W,W,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,22.0,22.0
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50,L,D,W,D,D,W,D,L,L,W,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,0,1,22.0,22.0
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47,D,D,L,W,W,L,D,L,L,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83,L,W,W,W,D,D,W,W,L,L,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43,D,L,D,L,D,W,L,D,L,L,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60,L,W,W,W,D,W,D,W,D,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47,L,L,L,L,W,D,D,D,L,L,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62,D,L,D,W,W,W,D,W,L,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49,W,L,W,L,L,D,W,L,L,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59,W,L,D,L,D,D,D,W,L,D,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,22.0,22.0
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84,W,D,D,D,L,W,D,D,L,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,22.0,22.0
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62,D,W,D,L,L,W,D,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,22.0,22.0
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52,L,L,D,L,L,W,D,D,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75,L,L,W,W,W,D,L,W,W,W,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28,L,D,D,W,L,L,L,L,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59,W,W,D,W,L,W,L,W,D,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,22.0,22.0
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49,L,W,L,D,L,D,L,D,W,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56,L,D,L,W,W,W,W,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,22.0,22.0
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61,W,W,D,L,W,L,W,L,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,22.0,22.0
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70,W,D,W,L,L,L,D,W,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,1,0,1,0,22.0,22.0
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70,D,D,W,W,L,L,L,W,W,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67,W,W,D,W,D,L,D,L,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,22.0,22.0

After jnc:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A,HomeTeamLP,AwayTeamLP,MW
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,D,M,M,M,L,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50,D,L,W,W,W,D,L,D,D,W,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,22.0,22.0,44
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66,W,L,L,L,L,L,D,W,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0,44
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58,W,W,L,L,D,L,D,L,D,L,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,22.0,22.0,44
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28,D,W,D,D,D,L,L,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,0,1,1,0,22.0,22.0,44
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74,D,W,L,L,W,W,W,W,D,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0,44
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73,L,D,L,D,D,W,W,W,W,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0,44
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88,D,W,D,W,W,W,D,L,W,W,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52,L,W,D,L,L,D,L,W,W,D,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0,45
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73,D,D,L,W,W,L,W,W,W,W,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,22.0,22.0,45
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50,L,D,W,D,D,W,D,L,L,W,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,0,1,22.0,22.0,45
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47,D,D,L,W,W,L,D,L,L,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0,45
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83,L,W,W,W,D,D,W,W,L,L,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0,45
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43,D,L,D,L,D,W,L,D,L,L,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0,45
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60,L,W,W,W,D,W,D,W,D,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47,L,L,L,L,W,D,D,D,L,L,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62,D,L,D,W,W,W,D,W,L,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49,W,L,W,L,L,D,W,L,L,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59,W,L,D,L,D,D,D,W,L,D,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,22.0,22.0,45
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84,W,D,D,D,L,W,D,D,L,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62,D,W,D,L,L,W,D,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,22.0,22.0,46
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52,L,L,D,L,L,W,D,D,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75,L,L,W,W,W,D,L,W,W,W,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28,L,D,D,W,L,L,L,L,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0,46
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59,W,W,D,W,L,W,L,W,D,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,22.0,22.0,46
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49,L,W,L,D,L,D,L,D,W,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0,46
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56,L,D,L,W,W,W,W,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,22.0,22.0,46
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61,W,W,D,L,W,L,W,L,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,22.0,22.0,46
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70,W,D,W,L,L,L,D,W,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,1,0,1,0,22.0,22.0,46
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70,D,D,W,W,L,L,L,W,W,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67,W,W,D,W,D,L,D,L,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46

In [16]:

# aqui

# Adds the teams points at the time of the older games devided by the week number MW.
def add_past_games_points_df_jnc(playing_stat, match_line):

    # Home team past matches points H [Home] ou A [Away].
    playing_stat['HM1_H_PTS'] = 0.0
    playing_stat['HM1_A_PTS'] = 0.0
    
    playing_stat['HM2_H_PTS'] = 0.0
    playing_stat['HM2_A_PTS'] = 0.0
    
    # playing_stat['HM3_H_PTS'] = 0.0
    # playing_stat['HM3_A_PTS'] = 0.0
    
    # playing_stat['HM4_H_PTS'] = 0.0
    # playing_stat['HM4_A_PTS'] = 0.0
    
    # playing_stat['HM5_H_PTS'] = 0.0
    # playing_stat['HM5_A_PTS'] = 0.0


    # Away team past matches points H [Home] ou A [Away].    
    playing_stat['AM1_H_PTS'] = 0.0
    playing_stat['AM1_A_PTS'] = 0.0
    
    playing_stat['AM2_H_PTS'] = 0.0
    playing_stat['AM2_A_PTS'] = 0.0
    
    # playing_stat['AM3_H_PTS'] = 0.0
    # playing_stat['AM3_A_PTS'] = 0.0
    
    # playing_stat['AM4_H_PTS'] = 0.0
    # playing_stat['AM4_A_PTS'] = 0.0
    
    # playing_stat['AM5_H_PTS'] = 0.0
    # playing_stat['AM5_A_PTS'] = 0.0
    
    
    for i in range(0, len(playing_stat)):
        homeTeam = playing_stat.iloc[i].HomeTeam
        awayTeam = playing_stat.iloc[i].AwayTeam
           
        # Generate the location_dic keys for the line for the home and away teams.
        dic_key_homeTeam = homeTeam + str(i)
        dic_key_awayTeam = awayTeam + str(i)

        matches_line_list_home = match_line[dic_key_homeTeam]
        matches_line_list_away = match_line[dic_key_awayTeam]
        
        
        ############
        ## Away Team
        
        # NOTE: I think that the list is in reverse order, the zero position is
        #       the first game and the last position is the last game.
        #       But we wan't to transverse from the last to the first.
        length_home = len(matches_line_list_home)
        if (length_home >= 1):
            game_res_index = matches_line_list_home[-1] # 0
            HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
            ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
            
            MW_prev_game = playing_stat.iloc[game_res_index]['MW']
            #HTP_prev_game /= float(MW_prev_game)
            #ATP_prev_game /= float(MW_prev_game)
            
            if (playing_stat.iloc[game_res_index]['HM1_A'] == 1):
                HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game 
            
            playing_stat.set_value(index=i, col='HM1_H_PTS', value=HTP_prev_game)
            playing_stat.set_value(index=i, col='HM1_A_PTS', value=ATP_prev_game)
            
        if (length_home >= 2):
            game_res_index = matches_line_list_home[-2]
            HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
            ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
            
            MW_prev_game = playing_stat.iloc[game_res_index]['MW']
            #HTP_prev_game /= float(MW_prev_game)
            #ATP_prev_game /= float(MW_prev_game)
            
            if (playing_stat.iloc[game_res_index]['HM2_A'] == 1):
                HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game 
            
            playing_stat.set_value(index=i, col='HM2_H_PTS', value=HTP_prev_game)
            playing_stat.set_value(index=i, col='HM2_A_PTS', value=ATP_prev_game)

        #if (length_home >= 3):
        #    game_res_index = matches_line_list_home[-3]
        #    HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
        #    ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
        #    
        #    MW_prev_game = playing_stat.iloc[game_res_index]['MW']
        #    #HTP_prev_game /= float(MW_prev_game)
        #    #ATP_prev_game /= float(MW_prev_game)
        #    
        #    if (playing_stat.iloc[game_res_index]['HM3_A'] == 1):
        #        HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game
        #    
        #    playing_stat.set_value(index=i, col='HM3_H_PTS', value=HTP_prev_game)
        #    playing_stat.set_value(index=i, col='HM3_A_PTS', value=ATP_prev_game)

        #if (length_home >= 4):
        #    game_res_index = matches_line_list_home[-4] # 0
        #    HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
        #    ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
        #    
        #    MW_prev_game = playing_stat.iloc[game_res_index]['MW']
        #    #HTP_prev_game /= float(MW_prev_game)
        #    #ATP_prev_game /= float(MW_prev_game)
        #    
        #    if (playing_stat.iloc[game_res_index]['HM4_A'] == 1):
        #        HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game 
        #    
        #    playing_stat.set_value(index=i, col='HM4_H_PTS', value=HTP_prev_game)
        #    playing_stat.set_value(index=i, col='HM4_A_PTS', value=ATP_prev_game)
        
        #if (length_home >= 5):
        #    game_res_index = matches_line_list_home[-5]
        #    HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
        #    ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
        #    
        #    MW_prev_game = playing_stat.iloc[game_res_index]['MW']
        #    #HTP_prev_game /= float(MW_prev_game)
        #    #ATP_prev_game /= float(MW_prev_game)
        #    
        #    if (playing_stat.iloc[game_res_index]['HM5_A'] == 1):
        #        HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game 
            
        #    playing_stat.set_value(index=i, col='HM5_H_PTS', value=HTP_prev_game)
        #    playing_stat.set_value(index=i, col='HM5_A_PTS', value=ATP_prev_game)

        
        ############
        ## Away Team
        
        length_away = len(matches_line_list_away)
        if (length_away >= 1):
            game_res_index = matches_line_list_away[-1] # 0
            HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
            ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
            
            MW_prev_game = playing_stat.iloc[game_res_index]['MW']
            #HTP_prev_game /= float(MW_prev_game)
            #ATP_prev_game /= float(MW_prev_game)
            
            if (playing_stat.iloc[game_res_index]['AM1_A'] == 1):
                HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game
            
            playing_stat.set_value(index=i, col='AM1_H_PTS', value=HTP_prev_game)
            playing_stat.set_value(index=i, col='AM1_A_PTS', value=ATP_prev_game)

        if (length_away >= 2):
            game_res_index = matches_line_list_away[-2] # 0
            HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
            ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
            
            MW_prev_game = playing_stat.iloc[game_res_index]['MW']
            #HTP_prev_game /= float(MW_prev_game)
            #ATP_prev_game /= float(MW_prev_game)
            
            if (playing_stat.iloc[game_res_index]['AM2_A'] == 1):
                HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game 
            
            playing_stat.set_value(index=i, col='AM2_H_PTS', value=HTP_prev_game)
            playing_stat.set_value(index=i, col='AM2_A_PTS', value=ATP_prev_game)

        #if (length_away >= 3):
        #    game_res_index = matches_line_list_away[-3] # 0
        #    HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
        #    ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
        #    
        #    MW_prev_game = playing_stat.iloc[game_res_index]['MW']
        #    #HTP_prev_game /= float(MW_prev_game)
        #    #ATP_prev_game /= float(MW_prev_game)
        #    
        #    if (playing_stat.iloc[game_res_index]['AM3_A'] == 1):
        #        HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game 
        #    
        #    playing_stat.set_value(index=i, col='AM3_H_PTS', value=HTP_prev_game)
        #    playing_stat.set_value(index=i, col='AM3_A_PTS', value=ATP_prev_game)#

        #if (length_away >= 4):
        #    game_res_index = matches_line_list_away[-4] # 0
        #    HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
        #    ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
        #    
        #    MW_prev_game = playing_stat.iloc[game_res_index]['MW']
        #    #HTP_prev_game /= float(MW_prev_game)
        #    #ATP_prev_game /= float(MW_prev_game)
        #    
        #    if (playing_stat.iloc[game_res_index]['AM4_A'] == 1):
        #        HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game 
        #
        #    playing_stat.set_value(index=i, col='AM4_H_PTS', value=HTP_prev_game)
        #    playing_stat.set_value(index=i, col='AM4_A_PTS', value=ATP_prev_game)

        #if (length_away >= 5):
        #    game_res_index = matches_line_list_away[-5] # 0
        #    HTP_prev_game = playing_stat.iloc[game_res_index]['HTP'] 
        #    ATP_prev_game = playing_stat.iloc[game_res_index]['ATP']
        #    
        #    MW_prev_game = playing_stat.iloc[game_res_index]['MW']
        #    #HTP_prev_game /= float(MW_prev_game)
        #    #ATP_prev_game /= float(MW_prev_game)
        #
        #    if (playing_stat.iloc[game_res_index]['AM5_A'] == 1):
        #        HTP_prev_game, ATP_prev_game =  ATP_prev_game, HTP_prev_game 
        #    
        #    playing_stat.set_value(index=i, col='AM5_H_PTS', value=HTP_prev_game)
        #    playing_stat.set_value(index=i, col='AM5_A_PTS', value=ATP_prev_game)


    return playing_stat    


    
print("Start past games points: ")
display(playing_statistics_1)
playing_statistics_1 = add_past_games_points_df_jnc(playing_statistics_1, match_line_1)

## Grava o ficheiro para análise em disco.
##playing_statistics_1.to_csv(loc + "zzz2015_output_dataset.csv")

print("After past games points: ")
display(playing_statistics_1.head(30))
    
   
playing_statistics_2 = add_past_games_points_df_jnc(playing_statistics_2, match_line_2)
playing_statistics_3 = add_past_games_points_df_jnc(playing_statistics_3, match_line_3)
playing_statistics_4 = add_past_games_points_df_jnc(playing_statistics_4, match_line_4)
playing_statistics_5 = add_past_games_points_df_jnc(playing_statistics_5, match_line_5)
playing_statistics_6 = add_past_games_points_df_jnc(playing_statistics_6, match_line_6)
playing_statistics_7 = add_past_games_points_df_jnc(playing_statistics_7, match_line_7)
playing_statistics_8 = add_past_games_points_df_jnc(playing_statistics_8, match_line_8)
playing_statistics_9 = add_past_games_points_df_jnc(playing_statistics_9, match_line_9)
playing_statistics_10 = add_past_games_points_df_jnc(playing_statistics_10, match_line_10)
playing_statistics_11 = add_past_games_points_df_jnc(playing_statistics_11, match_line_11)
playing_statistics_12 = add_past_games_points_df_jnc(playing_statistics_12, match_line_12)
playing_statistics_13 = add_past_games_points_df_jnc(playing_statistics_13, match_line_13)
playing_statistics_14 = add_past_games_points_df_jnc(playing_statistics_14, match_line_14)

Start past games points:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A,HomeTeamLP,AwayTeamLP,MW
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,D,M,M,M,L,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,2005-04-23,Sunderland,Leicester,2,1,H,71,45,39,44,85,50,D,L,W,W,W,D,L,D,D,W,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,22.0,22.0,44
523,2005-04-23,Watford,Sheffield United,0,0,D,50,55,57,51,48,66,W,L,L,L,L,L,D,W,W,D,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0,44
524,2005-04-23,Wigan,QPR,0,0,D,75,52,33,56,82,58,W,W,L,L,D,L,D,L,D,L,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,1,0,22.0,22.0,44
525,2005-04-23,Wolves,Rotherham,2,0,H,64,35,56,66,57,28,D,W,D,D,D,L,L,L,W,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,0,1,1,0,22.0,22.0,44
526,2005-04-24,Millwall,Preston,2,1,H,48,64,44,52,59,74,D,W,L,L,W,W,W,W,D,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0,44
527,2005-04-26,Leicester,Derby,1,0,H,46,66,46,52,50,73,L,D,L,D,D,W,W,W,W,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0,44
528,2005-04-29,West Ham,Sunderland,1,2,A,63,73,53,40,70,88,D,W,D,W,W,W,D,L,W,W,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
529,2005-04-30,Burnley,Plymouth,2,0,H,36,52,39,62,56,52,L,W,D,L,L,D,L,W,W,D,0,1,1,0,1,0,0,1,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0,45
530,2005-04-30,Coventry,Derby,6,2,H,54,66,69,53,49,73,D,D,L,W,W,L,W,W,W,W,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,0,1,22.0,22.0,45
531,2005-04-30,Gillingham,Cardiff,1,1,D,42,46,63,50,48,50,L,D,W,D,D,W,D,L,L,W,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,0,1,22.0,22.0,45
532,2005-04-30,Ipswich,Crewe,5,1,H,79,63,54,80,81,47,D,D,L,W,W,L,D,L,L,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0,45
533,2005-04-30,Preston,Wigan,1,1,D,65,75,54,33,74,83,L,W,W,W,D,D,W,W,L,L,0,1,1,0,0,1,1,0,1,0,1,0,0,1,0,1,1,0,1,0,22.0,22.0,45
534,2005-04-30,QPR,Nott'm Forest,2,1,H,52,39,56,62,59,43,D,L,D,L,D,W,L,D,L,L,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0,45
535,2005-04-30,Reading,Wolves,1,2,A,49,66,39,56,70,60,L,W,W,W,D,W,D,W,D,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
536,2005-04-30,Rotherham,Brighton,0,1,A,35,38,68,64,28,47,L,L,L,L,W,D,D,D,L,L,0,1,1,0,1,0,0,1,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
537,2005-04-30,Sheffield United,Millwall,0,1,A,55,50,51,45,67,62,D,L,D,W,W,W,D,W,L,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
538,2005-04-30,Stoke,Watford,0,1,A,36,50,36,57,61,49,W,L,W,L,L,D,W,L,L,L,0,1,1,0,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,22.0,22.0,45
539,2005-05-01,Leicester,Leeds,2,0,H,47,49,46,50,53,59,W,L,D,L,D,D,D,W,L,D,1,0,0,1,1,0,1,0,0,1,1,0,0,1,0,1,1,0,1,0,22.0,22.0,45
540,2005-05-08,Brighton,Ipswich,1,1,D,39,84,64,55,50,84,W,D,D,D,L,W,D,D,L,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46
541,2005-05-08,Cardiff,QPR,1,0,H,47,54,51,57,51,62,D,W,D,L,L,W,D,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,0,1,1,0,0,1,22.0,22.0,46
542,2005-05-08,Crewe,Coventry,2,1,H,64,60,85,71,47,52,L,L,D,L,L,W,D,D,L,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46
543,2005-05-08,Derby,Preston,3,1,H,68,66,59,55,73,75,L,L,W,W,W,D,L,W,W,W,0,1,0,1,1,0,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46
544,2005-05-08,Leeds,Rotherham,0,0,D,49,35,52,69,59,28,L,D,D,W,L,L,L,L,L,L,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0,46
545,2005-05-08,Millwall,Burnley,0,0,D,51,38,45,39,65,59,W,W,D,W,L,W,L,W,D,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,22.0,22.0,46
546,2005-05-08,Nott'm Forest,Gillingham,2,2,D,40,43,64,64,43,49,L,W,L,D,L,D,L,D,W,D,0,1,1,0,0,1,1,0,1,0,1,0,0,1,1,0,1,0,0,1,22.0,22.0,46
547,2005-05-08,Plymouth,Leicester,0,0,D,52,49,64,46,52,56,L,D,L,W,W,W,W,L,D,L,0,1,1,0,0,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,22.0,22.0,46
548,2005-05-08,Sunderland,Stoke,1,0,H,75,36,41,37,91,61,W,W,D,L,W,L,W,L,W,L,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,1,22.0,22.0,46
549,2005-05-08,Watford,West Ham,1,2,A,51,64,57,55,52,70,W,D,W,L,L,L,D,W,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,0,1,1,0,1,0,22.0,22.0,46
550,2005-05-08,Wigan,Reading,3,1,H,76,50,34,41,84,70,D,D,W,W,L,L,L,W,W,W,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46
551,2005-05-08,Wolves,Sheffield United,4,2,H,68,55,57,52,63,67,W,W,D,W,D,L,D,L,D,W,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,22.0,22.0,46

After past games points:

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HM1_H,HM1_A,HM2_H,HM2_A,HM3_H,HM3_A,HM4_H,HM4_A,HM5_H,HM5_A,AM1_H,AM1_A,AM2_H,AM2_A,AM3_H,AM3_A,AM4_H,AM4_A,AM5_H,AM5_A,HomeTeamLP,AwayTeamLP,MW,HM1_H_PTS,HM1_A_PTS,HM2_H_PTS,HM2_A_PTS,AM1_H_PTS,AM1_A_PTS,AM2_H_PTS,AM2_A_PTS
0,2004-08-07,Burnley,Sheffield United,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2004-08-07,Coventry,Sunderland,2,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2004-08-07,Crewe,Cardiff,2,2,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2004-08-07,Ipswich,Gillingham,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2004-08-07,Leeds,Derby,1,0,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2004-08-07,Leicester,West Ham,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2004-08-07,Plymouth,Millwall,0,0,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2004-08-07,Preston,Watford,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2004-08-07,QPR,Rotherham,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2004-08-07,Reading,Brighton,3,2,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2004-08-07,Wigan,Nott'm Forest,1,1,D,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2004-08-08,Stoke,Wolves,2,1,H,0,0,0,0,0,0,M,M,M,M,M,M,M,M,M,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.0,22.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2004-08-09,Watford,QPR,3,0,H,1,1,2,1,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2004-08-10,Brighton,Plymouth,0,2,A,2,0,3,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2004-08-10,Cardiff,Coventry,2,1,H,2,2,2,0,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2004-08-10,Gillingham,Leeds,2,1,H,1,1,2,0,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2004-08-10,Millwall,Wigan,0,2,A,0,1,0,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2004-08-10,Rotherham,Burnley,0,0,D,1,1,1,1,1,1,D,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2004-08-10,Sheffield United,Stoke,0,0,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2004-08-10,Sunderland,Crewe,3,1,H,0,2,2,2,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2004-08-10,West Ham,Reading,1,0,H,0,3,0,2,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2004-08-11,Derby,Leicester,1,2,A,0,0,1,0,0,1,L,M,M,M,M,D,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2004-08-11,Nott'm Forest,Ipswich,1,1,D,1,2,1,1,1,3,D,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2004-08-11,Wolves,Preston,2,2,D,1,2,2,1,0,3,L,M,M,M,M,W,M,M,M,M,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,22.0,22.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2004-08-13,Cardiff,Plymouth,0,1,A,4,2,3,0,4,4,W,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
25,2004-08-14,Brighton,Coventry,1,1,D,2,3,5,2,0,3,L,L,M,M,M,L,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3,1.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0
26,2004-08-14,Derby,Ipswich,3,2,H,1,3,3,2,0,4,L,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3,1.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0
27,2004-08-14,Gillingham,Preston,2,1,H,3,4,3,3,3,4,W,L,M,M,M,D,W,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0
28,2004-08-14,Millwall,Leicester,2,0,H,0,2,2,1,1,4,L,D,M,M,M,W,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
29,2004-08-14,Nott'm Forest,Crewe,2,2,D,2,3,2,5,2,1,D,D,M,M,M,L,D,M,M,M,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,22.0,22.0,3,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

# FINAL DATAFRAME

In [17]:
# MUITO IMPORTANTE: - Vou retirar o dataSet_1  [2004_2005.csv], não o vou adicionar na concatenação pois neste
#                     os dados das equipas dos anos anteriores não estão correctas e todas
#                     estão na 22º posição no ano anterior. Mas os dados dele já foram usados para os dados 
#                     do ano seguinte.

#playing_stat = pd.concat([playing_statistics_1,                        

playing_stat = pd.concat([playing_statistics_2,
                          playing_statistics_3,
                          playing_statistics_4,
                          playing_statistics_5,
                          playing_statistics_6,
                          playing_statistics_7,
                          playing_statistics_8,
                          playing_statistics_9,
                          playing_statistics_10,
                          playing_statistics_11,
                          playing_statistics_12,
                          playing_statistics_13,
                          playing_statistics_14], ignore_index=True)


# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

playing_stat['HTFormPtsStr'] = playing_stat['HM1'] + playing_stat['HM2'] + playing_stat['HM3'] + playing_stat['HM4'] + playing_stat['HM5']
playing_stat['ATFormPtsStr'] = playing_stat['AM1'] + playing_stat['AM2'] + playing_stat['AM3'] + playing_stat['AM4'] + playing_stat['AM5']

playing_stat['HTFormPts'] = playing_stat['HTFormPtsStr'].apply(get_form_points)
playing_stat['ATFormPts'] = playing_stat['ATFormPtsStr'].apply(get_form_points)

# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string[-3:] == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string[-3:] == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0
    
playing_stat['HTWinStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ws)
playing_stat['HTWinStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ws)
playing_stat['HTLossStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ls)
playing_stat['HTLossStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ls)

playing_stat['ATWinStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ws)
playing_stat['ATWinStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ws)
playing_stat['ATLossStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ls)
playing_stat['ATLossStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ls)

playing_stat.keys()

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTGS', 'ATGS',
       'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3', 'HM4', 'HM5', 'AM1',
       'AM2', 'AM3', 'AM4', 'AM5', 'HM1_H', 'HM1_A', 'HM2_H', 'HM2_A', 'HM3_H',
       'HM3_A', 'HM4_H', 'HM4_A', 'HM5_H', 'HM5_A', 'AM1_H', 'AM1_A', 'AM2_H',
       'AM2_A', 'AM3_H', 'AM3_A', 'AM4_H', 'AM4_A', 'AM5_H', 'AM5_A',
       'HomeTeamLP', 'AwayTeamLP', 'MW', 'HM1_H_PTS', 'HM1_A_PTS', 'HM2_H_PTS',
       'HM2_A_PTS', 'AM1_H_PTS', 'AM1_A_PTS', 'AM2_H_PTS', 'AM2_A_PTS',
       'HTFormPtsStr', 'ATFormPtsStr', 'HTFormPts', 'ATFormPts',
       'HTWinStreak3', 'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5',
       'ATWinStreak3', 'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5'],
      dtype='object')

In [18]:
# Get Goal Difference
playing_stat['HTGD'] = playing_stat['HTGS'] - playing_stat['HTGC']
playing_stat['ATGD'] = playing_stat['ATGS'] - playing_stat['ATGC']

# Diff in points
playing_stat['DiffPts'] = playing_stat['HTP'] - playing_stat['ATP']
playing_stat['DiffFormPts'] = playing_stat['HTFormPts'] - playing_stat['ATFormPts']

# Diff in last year positions
playing_stat['DiffLP'] = playing_stat['HomeTeamLP'] - playing_stat['AwayTeamLP']

In [19]:
# Scale DiffPts , DiffFormPts, HTGD, ATGD by Matchweek.
cols = ['HTGD','ATGD','DiffPts','DiffFormPts','HTP','ATP']
playing_stat.MW = playing_stat.MW.astype(float)

for col in cols:
    playing_stat[col] = playing_stat[col] / playing_stat.MW

In [20]:
def only_hw(my_str):
    if my_str == 'H':
        return 'H'
    else:
        return 'NH'
    
def all_types_of_results(my_str):
    if my_str == 'H':
        return '0'
    elif my_str == 'D':
        return '1'
    else:
        return '2'
    
#playing_stat['FTR'] = playing_stat.FTR.apply(only_hw)
playing_stat['FTR'] = playing_stat.FTR.apply(all_types_of_results)

# Testing set (2015-16 season)
# playing_stat_test = playing_stat[5700:]

In [21]:
playing_stat.to_csv(loc + "final_dataset.csv")
# playing_stat_test.to_csv(loc+"test.csv")

print("Finish!")

Finish!

In [22]:
# loc = "./backup_001/Datasets/"
# datafile_first = pd.read_csv(loc + "final_dataset.csv")

# loc = "./Datasets/"
# datafile_second = pd.read_csv(loc + "final_dataset.csv")

# print("datafile_first: ")
# display(datafile_first.tail())

# print("datafile_second: ")
# display(datafile_second.tail(30))